// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: orders/v1/orders.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.orders.v1;

@com.google.protobuf.Generated
public interface CreateOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.v1.CreateOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1 [json_name = "productId"];</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1 [json_name = "productId"];</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();
}
