// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: orders/v1/orders.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.orders.v1;

@com.google.protobuf.Generated
public interface GetAllOrdersRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:orders.v1.GetAllOrdersRequest)
    com.google.protobuf.MessageOrBuilder {
}
