services:

  admin-gateway:
    container_name: swiftmart-admin-gateway 
    image: biswasakash/swiftmart-admin-gateway:local
    ports:
      - "9000:9000"
    networks:
      - service-network

  template-engine:
    container_name: swiftmart-template-engine
    image: biswasakash/swiftmart-template-engine:local
    ports:
      - "9001:9001"
    networks:
      - service-network


  accounts:
    container_name: swiftmart-accounts 
    image: biswasakash/swiftmart-accounts:local
    ports:
      - "8501:8501"
    networks:
      - service-network

  orders:
    container_name: swiftmart-orders
    image: biswasakash/swiftmart-orders:local
    ports: 
      - "8502:8502"
    networks:
      - service-network

  catelogue:
    container_name: swiftmart-catelogue
    image: biswasakash/swiftmart-catelogue:local
    ports: 
      - "8503:8503"
    networks:
      - service-network

  inventory:
    container_name: swiftmart-inventory
    image: biswasakash/swiftmart-inventory:local
    ports: 
      - "8504:8504"
    networks:
      - service-network

  search-engine:
    container_name: swiftmart-search-engine
    image: biswasakash/swiftmart-search-engine:local
    ports: 
      - "8505:8505"
    networks:
      - service-network


  postgres:
    container_name: nexus-postgres
    image: postgres:18.3-bookworm
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres-network

  mongo:
    container_name: nexus-mongo
    image: mongo:8.0-noble
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
  postgres-network:
    driver: bridge
