spring:
  application:
    name: gateway
  profiles:
    active: dev
  graphql:
    http:
      path: /api/v1/graphql
server:
  port: 9000

clients:
  web:
    rest: http://localhost:3000
  accounts:
    rest: http://localhost:8501
    grpc: http://localhost:50051

jwt:
  secret: 1A50EF4F7AB1F6069BC04EEABFA52D66257D47E7FBBE0D7C1C20D2D88E9489C5
  issuer: https://nexussphere.com


