# Use postgres/example user/password credentials

services:

  postgres:
    container_name: swiftmart-postgres
    image: postgres:alpine3.24
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres-network

  mongo:
    container_name: swiftmart-mongo
    image: mongo:8.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: devpassword
    networks:
      - mongo-network

networks:
  postgres-network:
    driver: bridge
  mongo-network:
    driver: bridge
