
# Use postgres/example user/password credentials

services:

  postgres:
    container_name: swiftmart-postgres
    image: postgres:18.3-bookworm
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - postgres-network


  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
