services:
  gateway:
    container_name: swiftmart-template-engine
    image: biswasakash/swiftmart-template-engine:latest
    ports:
      - "9000:8080"

  web:
    container_name: swiftmart-web
    image: biswasakash/swiftmart-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - gateway

  accounts:
    container_name: swiftmart-accounts
    image: biswasakash/swiftmart-accounts:local
    ports:
      - "8501:8501"
    depends_on:
      - postgres
      - postgres

  orders:
    container_name: swiftmart-orders
    image: biswasakash/swiftmart-orders:local
    ports:
      - "8502:8080"
    depends_on:
      - postgres

  catelogue:
    container_name: swiftmart-catelogue
    image: biswasakash/swiftmart-catelogue:local
    ports:
      - "8503:8080"
    depends_on:
      - mongo

  inventory:
    container_name: swiftmart-inventory
    image: biswasakash/swiftmart-inventory:local
    ports:
      - "8504:8080"
    depends_on:
      - posgres

  semantic-search:
    container_name: swiftmart-search-engine
    image: biswasakash/swiftmart-search-engine:local
    ports:
      - "8505:8080"
    depends_on:
      - postgres

  template-agent:
    container_name: swiftmart-template-agent
    image: biswasakash/swiftmart-template-agent:local
    ports:
      - "8506:8080"
    depends_on:
      - mongo
  template-engine:
    container_name: swiftmart-template-engine
    image: biswasakash/swiftmart-template-engine:local
    ports:
      - "8507:8080"
    depends_on:
      - mongo

  postgres:
    container_name: swiftmart-postgres
    image: postgres:alpine3.24
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./scripts/postgres/setup.sql:/docker-entrypoint-initdb.d/setup.sql

  mongo:
    container_name: swiftmart-mongo
    image: mongo:8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=dev
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
