// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: products/v1/main.proto

package productsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku               string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Price             float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	InventoryQuantity uint32                 `protobuf:"varint,4,opt,name=inventory_quantity,json=inventoryQuantity,proto3" json:"inventory_quantity,omitempty"`
	Title             string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VariantMessage) Reset() {
	*x = VariantMessage{}
	mi := &file_products_v1_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantMessage) ProtoMessage() {}

func (x *VariantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantMessage.ProtoReflect.Descriptor instead.
func (*VariantMessage) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{0}
}

func (x *VariantMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VariantMessage) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *VariantMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *VariantMessage) GetInventoryQuantity() uint32 {
	if x != nil {
		return x.InventoryQuantity
	}
	return 0
}

func (x *VariantMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateVariantMessage struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Sku               string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Price             float64                `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	InventoryQuantity int32                  `protobuf:"varint,3,opt,name=inventory_quantity,json=inventoryQuantity,proto3" json:"inventory_quantity,omitempty"`
	Title             string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateVariantMessage) Reset() {
	*x = CreateVariantMessage{}
	mi := &file_products_v1_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariantMessage) ProtoMessage() {}

func (x *CreateVariantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariantMessage.ProtoReflect.Descriptor instead.
func (*CreateVariantMessage) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVariantMessage) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateVariantMessage) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateVariantMessage) GetInventoryQuantity() int32 {
	if x != nil {
		return x.InventoryQuantity
	}
	return 0
}

func (x *CreateVariantMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Variants      []*VariantMessage      `protobuf:"bytes,6,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductResponse) Reset() {
	*x = ProductResponse{}
	mi := &file_products_v1_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductResponse) ProtoMessage() {}

func (x *ProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductResponse.ProtoReflect.Descriptor instead.
func (*ProductResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{2}
}

func (x *ProductResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductResponse) GetVariants() []*VariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_products_v1_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductResponse       `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_products_v1_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductResponse) GetProduct() *ProductResponse {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateVariantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	QuantityDelta *int32                 `protobuf:"varint,2,opt,name=quantity_delta,json=quantityDelta,proto3,oneof" json:"quantity_delta,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Price         *uint32                `protobuf:"varint,4,opt,name=price,proto3,oneof" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariantRequest) Reset() {
	*x = UpdateVariantRequest{}
	mi := &file_products_v1_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantRequest) ProtoMessage() {}

func (x *UpdateVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariantRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVariantRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *UpdateVariantRequest) GetQuantityDelta() int32 {
	if x != nil && x.QuantityDelta != nil {
		return *x.QuantityDelta
	}
	return 0
}

func (x *UpdateVariantRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVariantRequest) GetPrice() uint32 {
	if x != nil && x.Price != nil {
		return *x.Price
	}
	return 0
}

type UpdateVariantResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VariantDetails *VariantMessage        `protobuf:"bytes,1,opt,name=variant_details,json=variantDetails,proto3" json:"variant_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateVariantResponse) Reset() {
	*x = UpdateVariantResponse{}
	mi := &file_products_v1_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantResponse) ProtoMessage() {}

func (x *UpdateVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantResponse.ProtoReflect.Descriptor instead.
func (*UpdateVariantResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVariantResponse) GetVariantDetails() *VariantMessage {
	if x != nil {
		return x.VariantDetails
	}
	return nil
}

type CreateProductRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Variants      []*CreateVariantMessage `protobuf:"bytes,4,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_products_v1_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateProductRequest) GetVariants() []*CreateVariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *emptypb.Empty         `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_products_v1_main_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResponse) GetRes() *emptypb.Empty {
	if x != nil {
		return x.Res
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,3,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_products_v1_main_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListProductsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListProductsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductResponse     `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_products_v1_main_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsResponse) GetProducts() []*ProductResponse {
	if x != nil {
		return x.Products
	}
	return nil
}

type AddVariantRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ProductId     string                  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Variants      []*CreateVariantMessage `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVariantRequest) Reset() {
	*x = AddVariantRequest{}
	mi := &file_products_v1_main_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVariantRequest) ProtoMessage() {}

func (x *AddVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVariantRequest.ProtoReflect.Descriptor instead.
func (*AddVariantRequest) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{11}
}

func (x *AddVariantRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddVariantRequest) GetVariants() []*CreateVariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

type AddVariantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *emptypb.Empty         `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVariantResponse) Reset() {
	*x = AddVariantResponse{}
	mi := &file_products_v1_main_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVariantResponse) ProtoMessage() {}

func (x *AddVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_products_v1_main_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVariantResponse.ProtoReflect.Descriptor instead.
func (*AddVariantResponse) Descriptor() ([]byte, []int) {
	return file_products_v1_main_proto_rawDescGZIP(), []int{12}
}

func (x *AddVariantResponse) GetRes() *emptypb.Empty {
	if x != nil {
		return x.Res
	}
	return nil
}

var File_products_v1_main_proto protoreflect.FileDescriptor

const file_products_v1_main_proto_rawDesc = "" +
	"\n" +
	"\x16products/v1/main.proto\x12\vproducts.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x8d\x01\n" +
	"\x0eVariantMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12-\n" +
	"\x12inventory_quantity\x18\x04 \x01(\rR\x11inventoryQuantity\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\"\x83\x01\n" +
	"\x14CreateVariantMessage\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x01R\x05price\x12-\n" +
	"\x12inventory_quantity\x18\x03 \x01(\x05R\x11inventoryQuantity\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xbe\x01\n" +
	"\x0fProductResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x127\n" +
	"\bvariants\x18\x06 \x03(\v2\x1b.products.v1.VariantMessageR\bvariants\"#\n" +
	"\x11GetProductRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"L\n" +
	"\x12GetProductResponse\x126\n" +
	"\aproduct\x18\x01 \x01(\v2\x1c.products.v1.ProductResponseR\aproduct\"\xbe\x01\n" +
	"\x14UpdateVariantRequest\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tR\tvariantId\x12*\n" +
	"\x0equantity_delta\x18\x02 \x01(\x05H\x00R\rquantityDelta\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x19\n" +
	"\x05price\x18\x04 \x01(\rH\x02R\x05price\x88\x01\x01B\x11\n" +
	"\x0f_quantity_deltaB\b\n" +
	"\x06_titleB\b\n" +
	"\x06_price\"]\n" +
	"\x15UpdateVariantResponse\x12D\n" +
	"\x0fvariant_details\x18\x01 \x01(\v2\x1b.products.v1.VariantMessageR\x0evariantDetails\"\xa1\x01\n" +
	"\x14CreateProductRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12=\n" +
	"\bvariants\x18\x04 \x03(\v2!.products.v1.CreateVariantMessageR\bvariants\"A\n" +
	"\x15CreateProductResponse\x12(\n" +
	"\x03res\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03res\"f\n" +
	"\x13ListProductsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12!\n" +
	"\fsearch_query\x18\x03 \x01(\tR\vsearchQuery\"P\n" +
	"\x14ListProductsResponse\x128\n" +
	"\bproducts\x18\x01 \x03(\v2\x1c.products.v1.ProductResponseR\bproducts\"q\n" +
	"\x11AddVariantRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12=\n" +
	"\bvariants\x18\x02 \x03(\v2!.products.v1.CreateVariantMessageR\bvariants\">\n" +
	"\x12AddVariantResponse\x12(\n" +
	"\x03res\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03res2\xb4\x03\n" +
	"\x0fProductsService\x12M\n" +
	"\n" +
	"GetProduct\x12\x1e.products.v1.GetProductRequest\x1a\x1f.products.v1.GetProductResponse\x12S\n" +
	"\fListProducts\x12 .products.v1.ListProductsRequest\x1a!.products.v1.ListProductsResponse\x12V\n" +
	"\rCreateProduct\x12!.products.v1.CreateProductRequest\x1a\".products.v1.CreateProductResponse\x12V\n" +
	"\rUpdateVariant\x12!.products.v1.UpdateVariantRequest\x1a\".products.v1.UpdateVariantResponse\x12M\n" +
	"\n" +
	"AddVariant\x12\x1e.products.v1.AddVariantRequest\x1a\x1f.products.v1.AddVariantResponseB\xaf\x01\n" +
	"\x0fcom.products.v1B\tMainProtoP\x01ZDgithub.com/biswasakashdev/swiftmart/services/gpql-gateway;productsv1\xa2\x02\x03PXX\xaa\x02\vProducts.V1\xca\x02\vProducts\\V1\xe2\x02\x17Products\\V1\\GPBMetadata\xea\x02\fProducts::V1b\x06proto3"

var (
	file_products_v1_main_proto_rawDescOnce sync.Once
	file_products_v1_main_proto_rawDescData []byte
)

func file_products_v1_main_proto_rawDescGZIP() []byte {
	file_products_v1_main_proto_rawDescOnce.Do(func() {
		file_products_v1_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_products_v1_main_proto_rawDesc), len(file_products_v1_main_proto_rawDesc)))
	})
	return file_products_v1_main_proto_rawDescData
}

var file_products_v1_main_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_products_v1_main_proto_goTypes = []any{
	(*VariantMessage)(nil),        // 0: products.v1.VariantMessage
	(*CreateVariantMessage)(nil),  // 1: products.v1.CreateVariantMessage
	(*ProductResponse)(nil),       // 2: products.v1.ProductResponse
	(*GetProductRequest)(nil),     // 3: products.v1.GetProductRequest
	(*GetProductResponse)(nil),    // 4: products.v1.GetProductResponse
	(*UpdateVariantRequest)(nil),  // 5: products.v1.UpdateVariantRequest
	(*UpdateVariantResponse)(nil), // 6: products.v1.UpdateVariantResponse
	(*CreateProductRequest)(nil),  // 7: products.v1.CreateProductRequest
	(*CreateProductResponse)(nil), // 8: products.v1.CreateProductResponse
	(*ListProductsRequest)(nil),   // 9: products.v1.ListProductsRequest
	(*ListProductsResponse)(nil),  // 10: products.v1.ListProductsResponse
	(*AddVariantRequest)(nil),     // 11: products.v1.AddVariantRequest
	(*AddVariantResponse)(nil),    // 12: products.v1.AddVariantResponse
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_products_v1_main_proto_depIdxs = []int32{
	0,  // 0: products.v1.ProductResponse.variants:type_name -> products.v1.VariantMessage
	2,  // 1: products.v1.GetProductResponse.product:type_name -> products.v1.ProductResponse
	0,  // 2: products.v1.UpdateVariantResponse.variant_details:type_name -> products.v1.VariantMessage
	1,  // 3: products.v1.CreateProductRequest.variants:type_name -> products.v1.CreateVariantMessage
	13, // 4: products.v1.CreateProductResponse.res:type_name -> google.protobuf.Empty
	2,  // 5: products.v1.ListProductsResponse.products:type_name -> products.v1.ProductResponse
	1,  // 6: products.v1.AddVariantRequest.variants:type_name -> products.v1.CreateVariantMessage
	13, // 7: products.v1.AddVariantResponse.res:type_name -> google.protobuf.Empty
	3,  // 8: products.v1.ProductsService.GetProduct:input_type -> products.v1.GetProductRequest
	9,  // 9: products.v1.ProductsService.ListProducts:input_type -> products.v1.ListProductsRequest
	7,  // 10: products.v1.ProductsService.CreateProduct:input_type -> products.v1.CreateProductRequest
	5,  // 11: products.v1.ProductsService.UpdateVariant:input_type -> products.v1.UpdateVariantRequest
	11, // 12: products.v1.ProductsService.AddVariant:input_type -> products.v1.AddVariantRequest
	4,  // 13: products.v1.ProductsService.GetProduct:output_type -> products.v1.GetProductResponse
	10, // 14: products.v1.ProductsService.ListProducts:output_type -> products.v1.ListProductsResponse
	8,  // 15: products.v1.ProductsService.CreateProduct:output_type -> products.v1.CreateProductResponse
	6,  // 16: products.v1.ProductsService.UpdateVariant:output_type -> products.v1.UpdateVariantResponse
	12, // 17: products.v1.ProductsService.AddVariant:output_type -> products.v1.AddVariantResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_products_v1_main_proto_init() }
func file_products_v1_main_proto_init() {
	if File_products_v1_main_proto != nil {
		return
	}
	file_products_v1_main_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_products_v1_main_proto_rawDesc), len(file_products_v1_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_products_v1_main_proto_goTypes,
		DependencyIndexes: file_products_v1_main_proto_depIdxs,
		MessageInfos:      file_products_v1_main_proto_msgTypes,
	}.Build()
	File_products_v1_main_proto = out.File
	file_products_v1_main_proto_goTypes = nil
	file_products_v1_main_proto_depIdxs = nil
}
