package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"fmt"

	"github.com/biswasakashdev/swiftmart/services/gateway/internal/gqlgen"
	"github.com/biswasakashdev/swiftmart/services/gateway/internal/graph/model"
)

// CreateProduct is the resolver for the createProduct field.
func (r *mutationResolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: CreateProduct - createProduct"))
}

// UpdateStock is the resolver for the updateStock field.
func (r *mutationResolver) UpdateStock(ctx context.Context, shopID string, variantID string, quantityDelta int32) (*model.ProductVariant, error) {
	panic(fmt.Errorf("not implemented: UpdateStock - updateStock"))
}

// Product is the resolver for the product field.
func (r *queryResolver) Product(ctx context.Context, shopID string, id string) (*model.Product, error) {
	panic(fmt.Errorf("not implemented: Product - product"))
}

// Products is the resolver for the products field.
func (r *queryResolver) Products(ctx context.Context, shopID string, pageInfo model.PageInfo, query *string) (*model.ProductList, error) {
	panic(fmt.Errorf("not implemented: Products - products"))
}

// Mutation returns gqlgen.MutationResolver implementation.
func (r *Resolver) Mutation() gqlgen.MutationResolver { return &mutationResolver{r} }

// Query returns gqlgen.QueryResolver implementation.
func (r *Resolver) Query() gqlgen.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
