spring:
  r2dbc:
    url: r2dbc:postgres://localhost:5432/swiftmart_accounts_test
    username: test
    password: testpassword
  sql:
    init:
      mode: always
      schema-locations:
        - classpath:db/schema/schema.sql