// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/Shops.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.core.v1;

/**
 * Protobuf type {@code core.v1.CreateShopResponse}
 */
@com.google.protobuf.Generated
public final class CreateShopResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:core.v1.CreateShopResponse)
    CreateShopResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "CreateShopResponse");
  }
  // Use CreateShopResponse.newBuilder() to construct.
  private CreateShopResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private CreateShopResponse() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.class, com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.Builder.class);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getUnknownFields().writeTo(output);
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse)) {
      return super.equals(obj);
    }
    com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse other = (com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse) obj;

    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code core.v1.CreateShopResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:core.v1.CreateShopResponse)
      com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.class, com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.Builder.class);
    }

    // Construct using com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.swiftmart.protogen.core.v1.ShopsProto.internal_static_core_v1_CreateShopResponse_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse getDefaultInstanceForType() {
      return com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse build() {
      com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse buildPartial() {
      com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse result = new com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse(this);
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse) {
        return mergeFrom((com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse other) {
      if (other == com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse.getDefaultInstance()) return this;
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    // @@protoc_insertion_point(builder_scope:core.v1.CreateShopResponse)
  }

  // @@protoc_insertion_point(class_scope:core.v1.CreateShopResponse)
  private static final com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse();
  }

  public static com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateShopResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateShopResponse>() {
    @java.lang.Override
    public CreateShopResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<CreateShopResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateShopResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.swiftmart.protogen.core.v1.CreateShopResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

