// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/Users.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.core.v1;

@com.google.protobuf.Generated
public interface CreateAccountResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:core.v1.CreateAccountResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Empty res = 1 [json_name = "res"];</code>
   * @return Whether the res field is set.
   */
  boolean hasRes();
  /**
   * <code>.google.protobuf.Empty res = 1 [json_name = "res"];</code>
   * @return The res.
   */
  com.google.protobuf.Empty getRes();
  /**
   * <code>.google.protobuf.Empty res = 1 [json_name = "res"];</code>
   */
  com.google.protobuf.EmptyOrBuilder getResOrBuilder();
}
