// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: core/v1/Users.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.core.v1;

@com.google.protobuf.Generated
public final class UsersProto extends com.google.protobuf.GeneratedFile {
  private UsersProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "UsersProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_CreateAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_CreateAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_CreateAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_CreateAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_AuthorizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_AuthorizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_AuthorizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_AuthorizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_AuthorizeResponse_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_AuthorizeResponse_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_core_v1_AuthorizeResponse_Authorization_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_core_v1_AuthorizeResponse_Authorization_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023core/v1/Users.proto\022\007core.v1\032\033google/p" +
      "rotobuf/empty.proto\"\316\001\n\024CreateAccountReq" +
      "uest\022\035\n\nfirst_name\030\001 \001(\tR\tfirstName\022\033\n\tl" +
      "ast_name\030\002 \001(\tR\010lastName\022\024\n\005email\030\003 \001(\tR" +
      "\005email\022\032\n\010password\030\004 \001(\tR\010password\022!\n\014co" +
      "untry_code\030\005 \001(\tR\013countryCode\022%\n\016contact" +
      "_number\030\006 \001(\tR\rcontactNumber\"A\n\025CreateAc" +
      "countResponse\022(\n\003res\030\001 \001(\0132\026.google.prot" +
      "obuf.EmptyR\003res\"D\n\020AuthorizeRequest\022\024\n\005e" +
      "mail\030\001 \001(\tR\005email\022\032\n\010password\030\002 \001(\tR\010pas" +
      "sword\"\333\002\n\021AuthorizeResponse\022P\n\rauthoriza" +
      "tion\030\001 \001(\0132(.core.v1.AuthorizeResponse.A" +
      "uthorizationH\000R\rauthorization\022\026\n\005error\030\002" +
      " \001(\tH\000R\005error\032`\n\014UserResponse\022\035\n\nfirst_n" +
      "ame\030\001 \001(\tR\tfirstName\022\033\n\tlast_name\030\002 \001(\tR" +
      "\010lastName\022\024\n\005email\030\003 \001(\tR\005email\032s\n\rAutho" +
      "rization\022L\n\ruser_response\030\001 \001(\0132\'.core.v" +
      "1.AuthorizeResponse.UserResponseR\014userRe" +
      "sponse\022\024\n\005token\030\002 \001(\tR\005tokenB\005\n\003res2\242\001\n\014" +
      "UsersService\022N\n\rCreateAccount\022\035.core.v1." +
      "CreateAccountRequest\032\036.core.v1.CreateAcc" +
      "ountResponse\022B\n\tAuthorize\022\031.core.v1.Auth" +
      "orizeRequest\032\032.core.v1.AuthorizeResponse" +
      "Bx\n-com.biswasakashdev.swiftmart.protoge" +
      "n.core.v1B\nUsersProtoP\001\242\002\003CXX\252\002\007Core.V1\312" +
      "\002\007Core\\V1\342\002\023Core\\V1\\GPBMetadata\352\002\010Core::" +
      "V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_core_v1_CreateAccountRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_core_v1_CreateAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_CreateAccountRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Password", "CountryCode", "ContactNumber", });
    internal_static_core_v1_CreateAccountResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_core_v1_CreateAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_CreateAccountResponse_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_core_v1_AuthorizeRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_core_v1_AuthorizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_AuthorizeRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_core_v1_AuthorizeResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_core_v1_AuthorizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_AuthorizeResponse_descriptor,
        new java.lang.String[] { "Authorization", "Error", "Res", });
    internal_static_core_v1_AuthorizeResponse_UserResponse_descriptor =
      internal_static_core_v1_AuthorizeResponse_descriptor.getNestedType(0);
    internal_static_core_v1_AuthorizeResponse_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_AuthorizeResponse_UserResponse_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", });
    internal_static_core_v1_AuthorizeResponse_Authorization_descriptor =
      internal_static_core_v1_AuthorizeResponse_descriptor.getNestedType(1);
    internal_static_core_v1_AuthorizeResponse_Authorization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_core_v1_AuthorizeResponse_Authorization_descriptor,
        new java.lang.String[] { "UserResponse", "Token", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
