// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: orders/v1/main.proto

package productsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_orders_v1_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_orders_v1_main_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

type CreateOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_orders_v1_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orders_v1_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_orders_v1_main_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

var File_orders_v1_main_proto protoreflect.FileDescriptor

const file_orders_v1_main_proto_rawDesc = "" +
	"\n" +
	"\x14orders/v1/main.proto\x12\torders.v1\"3\n" +
	"\x12CreateOrderRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\"4\n" +
	"\x13CreateOrderResponse\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId2\\\n" +
	"\fOrderService\x12L\n" +
	"\vCreateOrder\x12\x1d.orders.v1.CreateOrderRequest\x1a\x1e.orders.v1.CreateOrderResponseB\xa5\x01\n" +
	"\rcom.orders.v1B\tMainProtoP\x01ZDgithub.com/biswasakashdev/swiftmart/services/gpql-gateway;productsv1\xa2\x02\x03OXX\xaa\x02\tOrders.V1\xca\x02\tOrders\\V1\xe2\x02\x15Orders\\V1\\GPBMetadata\xea\x02\n" +
	"Orders::V1b\x06proto3"

var (
	file_orders_v1_main_proto_rawDescOnce sync.Once
	file_orders_v1_main_proto_rawDescData []byte
)

func file_orders_v1_main_proto_rawDescGZIP() []byte {
	file_orders_v1_main_proto_rawDescOnce.Do(func() {
		file_orders_v1_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orders_v1_main_proto_rawDesc), len(file_orders_v1_main_proto_rawDesc)))
	})
	return file_orders_v1_main_proto_rawDescData
}

var file_orders_v1_main_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_orders_v1_main_proto_goTypes = []any{
	(*CreateOrderRequest)(nil),  // 0: orders.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil), // 1: orders.v1.CreateOrderResponse
}
var file_orders_v1_main_proto_depIdxs = []int32{
	0, // 0: orders.v1.OrderService.CreateOrder:input_type -> orders.v1.CreateOrderRequest
	1, // 1: orders.v1.OrderService.CreateOrder:output_type -> orders.v1.CreateOrderResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_orders_v1_main_proto_init() }
func file_orders_v1_main_proto_init() {
	if File_orders_v1_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orders_v1_main_proto_rawDesc), len(file_orders_v1_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orders_v1_main_proto_goTypes,
		DependencyIndexes: file_orders_v1_main_proto_depIdxs,
		MessageInfos:      file_orders_v1_main_proto_msgTypes,
	}.Build()
	File_orders_v1_main_proto = out.File
	file_orders_v1_main_proto_goTypes = nil
	file_orders_v1_main_proto_depIdxs = nil
}
