// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.users.v1;

@com.google.protobuf.Generated
public interface AuthorizeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:users.v1.AuthorizeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.users.v1.AuthorizeResponse.Authorization authorization = 1 [json_name = "authorization"];</code>
   * @return Whether the authorization field is set.
   */
  boolean hasAuthorization();
  /**
   * <code>.users.v1.AuthorizeResponse.Authorization authorization = 1 [json_name = "authorization"];</code>
   * @return The authorization.
   */
  com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.Authorization getAuthorization();
  /**
   * <code>.users.v1.AuthorizeResponse.Authorization authorization = 1 [json_name = "authorization"];</code>
   */
  com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.AuthorizationOrBuilder getAuthorizationOrBuilder();

  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return Whether the error field is set.
   */
  boolean hasError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <code>string error = 2 [json_name = "error"];</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();

  com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.ResCase getResCase();
}
