// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.users.v1;

/**
 * Protobuf type {@code users.v1.AuthorizeResponse}
 */
@com.google.protobuf.Generated
public final class AuthorizeResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:users.v1.AuthorizeResponse)
    AuthorizeResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "AuthorizeResponse");
  }
  // Use AuthorizeResponse.newBuilder() to construct.
  private AuthorizeResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private AuthorizeResponse() {
    authorization_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.class, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.Builder.class);
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:users.v1.AuthorizeResponse.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string first_name = 1 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    java.lang.String getFirstName();
    /**
     * <code>string first_name = 1 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    com.google.protobuf.ByteString
        getFirstNameBytes();

    /**
     * <code>string last_name = 2 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    java.lang.String getLastName();
    /**
     * <code>string last_name = 2 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    com.google.protobuf.ByteString
        getLastNameBytes();

    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>string shop_image = 4 [json_name = "shopImage"];</code>
     * @return The shopImage.
     */
    java.lang.String getShopImage();
    /**
     * <code>string shop_image = 4 [json_name = "shopImage"];</code>
     * @return The bytes for shopImage.
     */
    com.google.protobuf.ByteString
        getShopImageBytes();
  }
  /**
   * Protobuf type {@code users.v1.AuthorizeResponse.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:users.v1.AuthorizeResponse.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 35,
        /* patch= */ 1,
        /* suffix= */ "",
        "User");
    }
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private User() {
      firstName_ = "";
      lastName_ = "";
      email_ = "";
      shopImage_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.class, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder.class);
    }

    public static final int FIRST_NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object firstName_ = "";
    /**
     * <code>string first_name = 1 [json_name = "firstName"];</code>
     * @return The firstName.
     */
    @java.lang.Override
    public java.lang.String getFirstName() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        firstName_ = s;
        return s;
      }
    }
    /**
     * <code>string first_name = 1 [json_name = "firstName"];</code>
     * @return The bytes for firstName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getFirstNameBytes() {
      java.lang.Object ref = firstName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        firstName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LAST_NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastName_ = "";
    /**
     * <code>string last_name = 2 [json_name = "lastName"];</code>
     * @return The lastName.
     */
    @java.lang.Override
    public java.lang.String getLastName() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastName_ = s;
        return s;
      }
    }
    /**
     * <code>string last_name = 2 [json_name = "lastName"];</code>
     * @return The bytes for lastName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastNameBytes() {
      java.lang.Object ref = lastName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object email_ = "";
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The email.
     */
    @java.lang.Override
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3 [json_name = "email"];</code>
     * @return The bytes for email.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SHOP_IMAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object shopImage_ = "";
    /**
     * <code>string shop_image = 4 [json_name = "shopImage"];</code>
     * @return The shopImage.
     */
    @java.lang.Override
    public java.lang.String getShopImage() {
      java.lang.Object ref = shopImage_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        shopImage_ = s;
        return s;
      }
    }
    /**
     * <code>string shop_image = 4 [json_name = "shopImage"];</code>
     * @return The bytes for shopImage.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getShopImageBytes() {
      java.lang.Object ref = shopImage_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        shopImage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shopImage_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, shopImage_);
      }
      getUnknownFields().writeTo(output);
    }
    private int computeSerializedSize_0() {
      int size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(firstName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, firstName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(lastName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, lastName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(email_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, email_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(shopImage_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, shopImage_);
      }
      return size;
    }
    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += computeSerializedSize_0();
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User)) {
        return super.equals(obj);
      }
      com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User other = (com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User) obj;

      if (!getFirstName()
          .equals(other.getFirstName())) return false;
      if (!getLastName()
          .equals(other.getLastName())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (!getShopImage()
          .equals(other.getShopImage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + FIRST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getFirstName().hashCode();
      hash = (37 * hash) + LAST_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getLastName().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      hash = (37 * hash) + SHOP_IMAGE_FIELD_NUMBER;
      hash = (53 * hash) + getShopImage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code users.v1.AuthorizeResponse.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:users.v1.AuthorizeResponse.User)
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.class, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder.class);
      }

      // Construct using com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        firstName_ = "";
        lastName_ = "";
        email_ = "";
        shopImage_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_User_descriptor;
      }

      @java.lang.Override
      public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User getDefaultInstanceForType() {
        return com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User build() {
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User buildPartial() {
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User result = new com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.firstName_ = firstName_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.lastName_ = lastName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.email_ = email_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.shopImage_ = shopImage_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User) {
          return mergeFrom((com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User other) {
        if (other == com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance()) return this;
        if (!other.getFirstName().isEmpty()) {
          firstName_ = other.firstName_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getLastName().isEmpty()) {
          lastName_ = other.lastName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getShopImage().isEmpty()) {
          shopImage_ = other.shopImage_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                firstName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                lastName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                email_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                shopImage_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object firstName_ = "";
      /**
       * <code>string first_name = 1 [json_name = "firstName"];</code>
       * @return The firstName.
       */
      public java.lang.String getFirstName() {
        java.lang.Object ref = firstName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          firstName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string first_name = 1 [json_name = "firstName"];</code>
       * @return The bytes for firstName.
       */
      public com.google.protobuf.ByteString
          getFirstNameBytes() {
        java.lang.Object ref = firstName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          firstName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string first_name = 1 [json_name = "firstName"];</code>
       * @param value The firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        firstName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1 [json_name = "firstName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearFirstName() {
        firstName_ = getDefaultInstance().getFirstName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string first_name = 1 [json_name = "firstName"];</code>
       * @param value The bytes for firstName to set.
       * @return This builder for chaining.
       */
      public Builder setFirstNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        firstName_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object lastName_ = "";
      /**
       * <code>string last_name = 2 [json_name = "lastName"];</code>
       * @return The lastName.
       */
      public java.lang.String getLastName() {
        java.lang.Object ref = lastName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_name = 2 [json_name = "lastName"];</code>
       * @return The bytes for lastName.
       */
      public com.google.protobuf.ByteString
          getLastNameBytes() {
        java.lang.Object ref = lastName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_name = 2 [json_name = "lastName"];</code>
       * @param value The lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2 [json_name = "lastName"];</code>
       * @return This builder for chaining.
       */
      public Builder clearLastName() {
        lastName_ = getDefaultInstance().getLastName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string last_name = 2 [json_name = "lastName"];</code>
       * @param value The bytes for lastName to set.
       * @return This builder for chaining.
       */
      public Builder setLastNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        email_ = getDefaultInstance().getEmail();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3 [json_name = "email"];</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        email_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object shopImage_ = "";
      /**
       * <code>string shop_image = 4 [json_name = "shopImage"];</code>
       * @return The shopImage.
       */
      public java.lang.String getShopImage() {
        java.lang.Object ref = shopImage_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          shopImage_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string shop_image = 4 [json_name = "shopImage"];</code>
       * @return The bytes for shopImage.
       */
      public com.google.protobuf.ByteString
          getShopImageBytes() {
        java.lang.Object ref = shopImage_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          shopImage_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string shop_image = 4 [json_name = "shopImage"];</code>
       * @param value The shopImage to set.
       * @return This builder for chaining.
       */
      public Builder setShopImage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        shopImage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string shop_image = 4 [json_name = "shopImage"];</code>
       * @return This builder for chaining.
       */
      public Builder clearShopImage() {
        shopImage_ = getDefaultInstance().getShopImage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string shop_image = 4 [json_name = "shopImage"];</code>
       * @param value The bytes for shopImage to set.
       * @return This builder for chaining.
       */
      public Builder setShopImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        shopImage_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:users.v1.AuthorizeResponse.User)
    }

    // @@protoc_insertion_point(class_scope:users.v1.AuthorizeResponse.User)
    private static final com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User();
    }

    public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int USER_FIELD_NUMBER = 1;
  private com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User user_;
  /**
   * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  @java.lang.Override
  public boolean hasUser() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  @java.lang.Override
  public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User getUser() {
    return user_ == null ? com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance() : user_;
  }
  /**
   * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
   */
  @java.lang.Override
  public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder getUserOrBuilder() {
    return user_ == null ? com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance() : user_;
  }

  public static final int AUTHORIZATION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object authorization_ = "";
  /**
   * <code>string authorization = 2 [json_name = "authorization"];</code>
   * @return The authorization.
   */
  @java.lang.Override
  public java.lang.String getAuthorization() {
    java.lang.Object ref = authorization_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      authorization_ = s;
      return s;
    }
  }
  /**
   * <code>string authorization = 2 [json_name = "authorization"];</code>
   * @return The bytes for authorization.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAuthorizationBytes() {
    java.lang.Object ref = authorization_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      authorization_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getUser());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorization_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, authorization_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getUser());
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(authorization_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, authorization_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse)) {
      return super.equals(obj);
    }
    com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse other = (com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse) obj;

    if (hasUser() != other.hasUser()) return false;
    if (hasUser()) {
      if (!getUser()
          .equals(other.getUser())) return false;
    }
    if (!getAuthorization()
        .equals(other.getAuthorization())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasUser()) {
      hash = (37 * hash) + USER_FIELD_NUMBER;
      hash = (53 * hash) + getUser().hashCode();
    }
    hash = (37 * hash) + AUTHORIZATION_FIELD_NUMBER;
    hash = (53 * hash) + getAuthorization().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code users.v1.AuthorizeResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:users.v1.AuthorizeResponse)
      com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.class, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.Builder.class);
    }

    // Construct using com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetUserFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      authorization_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.MainProto.internal_static_users_v1_AuthorizeResponse_descriptor;
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse getDefaultInstanceForType() {
      return com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse build() {
      com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse buildPartial() {
      com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse result = new com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.user_ = userBuilder_ == null
            ? user_
            : userBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.authorization_ = authorization_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse) {
        return mergeFrom((com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse other) {
      if (other == com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.getDefaultInstance()) return this;
      if (other.hasUser()) {
        mergeUser(other.getUser());
      }
      if (!other.getAuthorization().isEmpty()) {
        authorization_ = other.authorization_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetUserFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              authorization_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User user_;
    private com.google.protobuf.SingleFieldBuilder<
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder> userBuilder_;
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     * @return Whether the user field is set.
     */
    public boolean hasUser() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     * @return The user.
     */
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User getUser() {
      if (userBuilder_ == null) {
        return user_ == null ? com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance() : user_;
      } else {
        return userBuilder_.getMessage();
      }
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public Builder setUser(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User value) {
      if (userBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        user_ = value;
      } else {
        userBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public Builder setUser(
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder builderForValue) {
      if (userBuilder_ == null) {
        user_ = builderForValue.build();
      } else {
        userBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public Builder mergeUser(com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User value) {
      if (userBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          user_ != null &&
          user_ != com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance()) {
          getUserBuilder().mergeFrom(value);
        } else {
          user_ = value;
        }
      } else {
        userBuilder_.mergeFrom(value);
      }
      if (user_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public Builder clearUser() {
      bitField0_ = (bitField0_ & ~0x00000001);
      user_ = null;
      if (userBuilder_ != null) {
        userBuilder_.dispose();
        userBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder getUserBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetUserFieldBuilder().getBuilder();
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder getUserOrBuilder() {
      if (userBuilder_ != null) {
        return userBuilder_.getMessageOrBuilder();
      } else {
        return user_ == null ?
            com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.getDefaultInstance() : user_;
      }
    }
    /**
     * <code>.users.v1.AuthorizeResponse.User user = 1 [json_name = "user"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder> 
        internalGetUserFieldBuilder() {
      if (userBuilder_ == null) {
        userBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.User.Builder, com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse.UserOrBuilder>(
                getUser(),
                getParentForChildren(),
                isClean());
        user_ = null;
      }
      return userBuilder_;
    }

    private java.lang.Object authorization_ = "";
    /**
     * <code>string authorization = 2 [json_name = "authorization"];</code>
     * @return The authorization.
     */
    public java.lang.String getAuthorization() {
      java.lang.Object ref = authorization_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        authorization_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string authorization = 2 [json_name = "authorization"];</code>
     * @return The bytes for authorization.
     */
    public com.google.protobuf.ByteString
        getAuthorizationBytes() {
      java.lang.Object ref = authorization_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        authorization_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string authorization = 2 [json_name = "authorization"];</code>
     * @param value The authorization to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorization(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      authorization_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string authorization = 2 [json_name = "authorization"];</code>
     * @return This builder for chaining.
     */
    public Builder clearAuthorization() {
      authorization_ = getDefaultInstance().getAuthorization();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string authorization = 2 [json_name = "authorization"];</code>
     * @param value The bytes for authorization to set.
     * @return This builder for chaining.
     */
    public Builder setAuthorizationBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      authorization_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:users.v1.AuthorizeResponse)
  }

  // @@protoc_insertion_point(class_scope:users.v1.AuthorizeResponse)
  private static final com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse();
  }

  public static com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AuthorizeResponse>
      PARSER = new com.google.protobuf.AbstractParser<AuthorizeResponse>() {
    @java.lang.Override
    public AuthorizeResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<AuthorizeResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AuthorizeResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.biswasakashdev.swiftmart.protogen.users.v1.AuthorizeResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

