// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.users.v1;

@com.google.protobuf.Generated
public final class MainProto extends com.google.protobuf.GeneratedFile {
  private MainProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MainProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_CreateAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_CreateAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_CreateAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_CreateAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeResponse_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeResponse_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023users/v1/main.proto\022\010users.v1\032\033google/" +
      "protobuf/empty.proto\"\262\001\n\024CreateAccountRe" +
      "quest\022\035\n\nfirst_name\030\001 \001(\tR\tfirstName\022\033\n\t" +
      "last_name\030\002 \001(\tR\010lastName\022\024\n\005email\030\003 \001(\t" +
      "R\005email\022!\n\014country_code\030\004 \001(\tR\013countryCo" +
      "de\022%\n\016contact_number\030\005 \001(\tR\rcontactNumbe" +
      "r\"A\n\025CreateAccountResponse\022(\n\003res\030\001 \001(\0132" +
      "\026.google.protobuf.EmptyR\003res\"D\n\020Authoriz" +
      "eRequest\022\024\n\005email\030\001 \001(\tR\005email\022\032\n\010passwo" +
      "rd\030\002 \001(\tR\010password\"\350\001\n\021AuthorizeResponse" +
      "\0224\n\004user\030\001 \001(\0132 .users.v1.AuthorizeRespo" +
      "nse.UserR\004user\022$\n\rauthorization\030\002 \001(\tR\ra" +
      "uthorization\032w\n\004User\022\035\n\nfirst_name\030\001 \001(\t" +
      "R\tfirstName\022\033\n\tlast_name\030\002 \001(\tR\010lastName" +
      "\022\024\n\005email\030\003 \001(\tR\005email\022\035\n\nshop_image\030\004 \001" +
      "(\tR\tshopImage2\246\001\n\014UsersService\022P\n\rCreate" +
      "Account\022\036.users.v1.CreateAccountRequest\032" +
      "\037.users.v1.CreateAccountResponse\022D\n\tAuth" +
      "orize\022\032.users.v1.AuthorizeRequest\032\033.user" +
      "s.v1.AuthorizeResponseB|\n.com.biswasakas" +
      "hdev.swiftmart.protogen.users.v1B\tMainPr" +
      "otoP\001\242\002\003UXX\252\002\010Users.V1\312\002\010Users\\V1\342\002\024User" +
      "s\\V1\\GPBMetadata\352\002\tUsers::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_users_v1_CreateAccountRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_users_v1_CreateAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_CreateAccountRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "CountryCode", "ContactNumber", });
    internal_static_users_v1_CreateAccountResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_users_v1_CreateAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_CreateAccountResponse_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_users_v1_AuthorizeRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_users_v1_AuthorizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_users_v1_AuthorizeResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_users_v1_AuthorizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeResponse_descriptor,
        new java.lang.String[] { "User", "Authorization", });
    internal_static_users_v1_AuthorizeResponse_User_descriptor =
      internal_static_users_v1_AuthorizeResponse_descriptor.getNestedType(0);
    internal_static_users_v1_AuthorizeResponse_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeResponse_User_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "ShopImage", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
