// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: users/v1/main.proto
// Protobuf Java Version: 4.35.1

package com.biswasakashdev.swiftmart.protogen.users.v1;

@com.google.protobuf.Generated
public final class MainProto extends com.google.protobuf.GeneratedFile {
  private MainProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "MainProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_CreateAccountRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_CreateAccountRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_CreateAccountResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_CreateAccountResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeResponse_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeResponse_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_users_v1_AuthorizeResponse_Authorization_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_users_v1_AuthorizeResponse_Authorization_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023users/v1/main.proto\022\010users.v1\032\033google/" +
      "protobuf/empty.proto\"\316\001\n\024CreateAccountRe" +
      "quest\022\035\n\nfirst_name\030\001 \001(\tR\tfirstName\022\033\n\t" +
      "last_name\030\002 \001(\tR\010lastName\022\024\n\005email\030\003 \001(\t" +
      "R\005email\022\032\n\010password\030\004 \001(\tR\010password\022!\n\014c" +
      "ountry_code\030\005 \001(\tR\013countryCode\022%\n\016contac" +
      "t_number\030\006 \001(\tR\rcontactNumber\"A\n\025CreateA" +
      "ccountResponse\022(\n\003res\030\001 \001(\0132\026.google.pro" +
      "tobuf.EmptyR\003res\"D\n\020AuthorizeRequest\022\024\n\005" +
      "email\030\001 \001(\tR\005email\022\032\n\010password\030\002 \001(\tR\010pa" +
      "ssword\"\335\002\n\021AuthorizeResponse\022Q\n\rauthoriz" +
      "ation\030\001 \001(\0132).users.v1.AuthorizeResponse" +
      ".AuthorizationH\000R\rauthorization\022\026\n\005error" +
      "\030\002 \001(\tH\000R\005error\032`\n\014UserResponse\022\035\n\nfirst" +
      "_name\030\001 \001(\tR\tfirstName\022\033\n\tlast_name\030\002 \001(" +
      "\tR\010lastName\022\024\n\005email\030\003 \001(\tR\005email\032t\n\rAut" +
      "horization\022M\n\ruser_response\030\001 \001(\0132(.user" +
      "s.v1.AuthorizeResponse.UserResponseR\014use" +
      "rResponse\022\024\n\005token\030\002 \001(\tR\005tokenB\005\n\003res2\246" +
      "\001\n\014UsersService\022P\n\rCreateAccount\022\036.users" +
      ".v1.CreateAccountRequest\032\037.users.v1.Crea" +
      "teAccountResponse\022D\n\tAuthorize\022\032.users.v" +
      "1.AuthorizeRequest\032\033.users.v1.AuthorizeR" +
      "esponseB|\n.com.biswasakashdev.swiftmart." +
      "protogen.users.v1B\tMainProtoP\001\242\002\003UXX\252\002\010U" +
      "sers.V1\312\002\010Users\\V1\342\002\024Users\\V1\\GPBMetadat" +
      "a\352\002\tUsers::V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        });
    internal_static_users_v1_CreateAccountRequest_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_users_v1_CreateAccountRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_CreateAccountRequest_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", "Password", "CountryCode", "ContactNumber", });
    internal_static_users_v1_CreateAccountResponse_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_users_v1_CreateAccountResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_CreateAccountResponse_descriptor,
        new java.lang.String[] { "Res", });
    internal_static_users_v1_AuthorizeRequest_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_users_v1_AuthorizeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeRequest_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_users_v1_AuthorizeResponse_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_users_v1_AuthorizeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeResponse_descriptor,
        new java.lang.String[] { "Authorization", "Error", "Res", });
    internal_static_users_v1_AuthorizeResponse_UserResponse_descriptor =
      internal_static_users_v1_AuthorizeResponse_descriptor.getNestedType(0);
    internal_static_users_v1_AuthorizeResponse_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeResponse_UserResponse_descriptor,
        new java.lang.String[] { "FirstName", "LastName", "Email", });
    internal_static_users_v1_AuthorizeResponse_Authorization_descriptor =
      internal_static_users_v1_AuthorizeResponse_descriptor.getNestedType(1);
    internal_static_users_v1_AuthorizeResponse_Authorization_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_users_v1_AuthorizeResponse_Authorization_descriptor,
        new java.lang.String[] { "UserResponse", "Token", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
