// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/v1/shops.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Create Shop
type CreateShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopRequest) Reset() {
	*x = CreateShopRequest{}
	mi := &file_core_v1_shops_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopRequest) ProtoMessage() {}

func (x *CreateShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopRequest.ProtoReflect.Descriptor instead.
func (*CreateShopRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{0}
}

type CreateShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *emptypb.Empty         `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateShopResponse) Reset() {
	*x = CreateShopResponse{}
	mi := &file_core_v1_shops_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShopResponse) ProtoMessage() {}

func (x *CreateShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShopResponse.ProtoReflect.Descriptor instead.
func (*CreateShopResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{1}
}

func (x *CreateShopResponse) GetRes() *emptypb.Empty {
	if x != nil {
		return x.Res
	}
	return nil
}

// GetAllShops
type GetAllShopsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllShopsRequest) Reset() {
	*x = GetAllShopsRequest{}
	mi := &file_core_v1_shops_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllShopsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShopsRequest) ProtoMessage() {}

func (x *GetAllShopsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShopsRequest.ProtoReflect.Descriptor instead.
func (*GetAllShopsRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{2}
}

type GetAllShopsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllShopsResponse) Reset() {
	*x = GetAllShopsResponse{}
	mi := &file_core_v1_shops_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllShopsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllShopsResponse) ProtoMessage() {}

func (x *GetAllShopsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllShopsResponse.ProtoReflect.Descriptor instead.
func (*GetAllShopsResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{3}
}

type GetShopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopRequest) Reset() {
	*x = GetShopRequest{}
	mi := &file_core_v1_shops_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopRequest) ProtoMessage() {}

func (x *GetShopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopRequest.ProtoReflect.Descriptor instead.
func (*GetShopRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{4}
}

type GetShopResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShopResponse) Reset() {
	*x = GetShopResponse{}
	mi := &file_core_v1_shops_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShopResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShopResponse) ProtoMessage() {}

func (x *GetShopResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_shops_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShopResponse.ProtoReflect.Descriptor instead.
func (*GetShopResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_shops_proto_rawDescGZIP(), []int{5}
}

var File_core_v1_shops_proto protoreflect.FileDescriptor

const file_core_v1_shops_proto_rawDesc = "" +
	"\n" +
	"\x13core/v1/shops.proto\x12\acore.v1\x1a\x1bgoogle/protobuf/empty.proto\"\x13\n" +
	"\x11CreateShopRequest\">\n" +
	"\x12CreateShopResponse\x12(\n" +
	"\x03res\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03res\"\x14\n" +
	"\x12GetAllShopsRequest\"\x15\n" +
	"\x13GetAllShopsResponse\"\x10\n" +
	"\x0eGetShopRequest\"\x11\n" +
	"\x0fGetShopResponse2\xdd\x01\n" +
	"\fShopsService\x12E\n" +
	"\n" +
	"CreateShop\x12\x1a.core.v1.CreateShopRequest\x1a\x1b.core.v1.CreateShopResponse\x12H\n" +
	"\vGetAllShops\x12\x1b.core.v1.GetAllShopsRequest\x1a\x1c.core.v1.GetAllShopsResponse\x12<\n" +
	"\aGetShop\x12\x17.core.v1.GetShopRequest\x1a\x18.core.v1.GetShopResponseB\x97\x01\n" +
	"\vcom.core.v1B\n" +
	"ShopsProtoP\x01Z?github.com/biswasakashdev/swiftmart/proto_gen/go/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_shops_proto_rawDescOnce sync.Once
	file_core_v1_shops_proto_rawDescData []byte
)

func file_core_v1_shops_proto_rawDescGZIP() []byte {
	file_core_v1_shops_proto_rawDescOnce.Do(func() {
		file_core_v1_shops_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_shops_proto_rawDesc), len(file_core_v1_shops_proto_rawDesc)))
	})
	return file_core_v1_shops_proto_rawDescData
}

var file_core_v1_shops_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_v1_shops_proto_goTypes = []any{
	(*CreateShopRequest)(nil),   // 0: core.v1.CreateShopRequest
	(*CreateShopResponse)(nil),  // 1: core.v1.CreateShopResponse
	(*GetAllShopsRequest)(nil),  // 2: core.v1.GetAllShopsRequest
	(*GetAllShopsResponse)(nil), // 3: core.v1.GetAllShopsResponse
	(*GetShopRequest)(nil),      // 4: core.v1.GetShopRequest
	(*GetShopResponse)(nil),     // 5: core.v1.GetShopResponse
	(*emptypb.Empty)(nil),       // 6: google.protobuf.Empty
}
var file_core_v1_shops_proto_depIdxs = []int32{
	6, // 0: core.v1.CreateShopResponse.res:type_name -> google.protobuf.Empty
	0, // 1: core.v1.ShopsService.CreateShop:input_type -> core.v1.CreateShopRequest
	2, // 2: core.v1.ShopsService.GetAllShops:input_type -> core.v1.GetAllShopsRequest
	4, // 3: core.v1.ShopsService.GetShop:input_type -> core.v1.GetShopRequest
	1, // 4: core.v1.ShopsService.CreateShop:output_type -> core.v1.CreateShopResponse
	3, // 5: core.v1.ShopsService.GetAllShops:output_type -> core.v1.GetAllShopsResponse
	5, // 6: core.v1.ShopsService.GetShop:output_type -> core.v1.GetShopResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_core_v1_shops_proto_init() }
func file_core_v1_shops_proto_init() {
	if File_core_v1_shops_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_shops_proto_rawDesc), len(file_core_v1_shops_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_shops_proto_goTypes,
		DependencyIndexes: file_core_v1_shops_proto_depIdxs,
		MessageInfos:      file_core_v1_shops_proto_msgTypes,
	}.Build()
	File_core_v1_shops_proto = out.File
	file_core_v1_shops_proto_goTypes = nil
	file_core_v1_shops_proto_depIdxs = nil
}
