// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: core/v1/shops.proto

package corev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShopsService_CreateShop_FullMethodName  = "/core.v1.ShopsService/CreateShop"
	ShopsService_GetAllShops_FullMethodName = "/core.v1.ShopsService/GetAllShops"
	ShopsService_GetShop_FullMethodName     = "/core.v1.ShopsService/GetShop"
)

// ShopsServiceClient is the client API for ShopsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShopsServiceClient interface {
	CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopResponse, error)
	GetAllShops(ctx context.Context, in *GetAllShopsRequest, opts ...grpc.CallOption) (*GetAllShopsResponse, error)
	GetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*GetShopResponse, error)
}

type shopsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShopsServiceClient(cc grpc.ClientConnInterface) ShopsServiceClient {
	return &shopsServiceClient{cc}
}

func (c *shopsServiceClient) CreateShop(ctx context.Context, in *CreateShopRequest, opts ...grpc.CallOption) (*CreateShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateShopResponse)
	err := c.cc.Invoke(ctx, ShopsService_CreateShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopsServiceClient) GetAllShops(ctx context.Context, in *GetAllShopsRequest, opts ...grpc.CallOption) (*GetAllShopsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllShopsResponse)
	err := c.cc.Invoke(ctx, ShopsService_GetAllShops_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shopsServiceClient) GetShop(ctx context.Context, in *GetShopRequest, opts ...grpc.CallOption) (*GetShopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShopResponse)
	err := c.cc.Invoke(ctx, ShopsService_GetShop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShopsServiceServer is the server API for ShopsService service.
// All implementations must embed UnimplementedShopsServiceServer
// for forward compatibility.
type ShopsServiceServer interface {
	CreateShop(context.Context, *CreateShopRequest) (*CreateShopResponse, error)
	GetAllShops(context.Context, *GetAllShopsRequest) (*GetAllShopsResponse, error)
	GetShop(context.Context, *GetShopRequest) (*GetShopResponse, error)
	mustEmbedUnimplementedShopsServiceServer()
}

// UnimplementedShopsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShopsServiceServer struct{}

func (UnimplementedShopsServiceServer) CreateShop(context.Context, *CreateShopRequest) (*CreateShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateShop not implemented")
}
func (UnimplementedShopsServiceServer) GetAllShops(context.Context, *GetAllShopsRequest) (*GetAllShopsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAllShops not implemented")
}
func (UnimplementedShopsServiceServer) GetShop(context.Context, *GetShopRequest) (*GetShopResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetShop not implemented")
}
func (UnimplementedShopsServiceServer) mustEmbedUnimplementedShopsServiceServer() {}
func (UnimplementedShopsServiceServer) testEmbeddedByValue()                      {}

// UnsafeShopsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShopsServiceServer will
// result in compilation errors.
type UnsafeShopsServiceServer interface {
	mustEmbedUnimplementedShopsServiceServer()
}

func RegisterShopsServiceServer(s grpc.ServiceRegistrar, srv ShopsServiceServer) {
	// If the following call panics, it indicates UnimplementedShopsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShopsService_ServiceDesc, srv)
}

func _ShopsService_CreateShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopsServiceServer).CreateShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopsService_CreateShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopsServiceServer).CreateShop(ctx, req.(*CreateShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopsService_GetAllShops_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllShopsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopsServiceServer).GetAllShops(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopsService_GetAllShops_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopsServiceServer).GetAllShops(ctx, req.(*GetAllShopsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShopsService_GetShop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShopsServiceServer).GetShop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShopsService_GetShop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShopsServiceServer).GetShop(ctx, req.(*GetShopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ShopsService_ServiceDesc is the grpc.ServiceDesc for ShopsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShopsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core.v1.ShopsService",
	HandlerType: (*ShopsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateShop",
			Handler:    _ShopsService_CreateShop_Handler,
		},
		{
			MethodName: "GetAllShops",
			Handler:    _ShopsService_GetAllShops_Handler,
		},
		{
			MethodName: "GetShop",
			Handler:    _ShopsService_GetShop_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "core/v1/shops.proto",
}
