// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: core/v1/users.proto

package corev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	CountryCode   string                 `protobuf:"bytes,5,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	ContactNumber string                 `protobuf:"bytes,6,opt,name=contact_number,json=contactNumber,proto3" json:"contact_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_core_v1_users_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAccountRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateAccountRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateAccountRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CreateAccountRequest) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CreateAccountRequest) GetContactNumber() string {
	if x != nil {
		return x.ContactNumber
	}
	return ""
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *emptypb.Empty         `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_core_v1_users_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetRes() *emptypb.Empty {
	if x != nil {
		return x.Res
	}
	return nil
}

type AuthorizeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_core_v1_users_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeRequest.ProtoReflect.Descriptor instead.
func (*AuthorizeRequest) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizeRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AuthorizeRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type AuthorizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Res:
	//
	//	*AuthorizeResponse_Authorization_
	//	*AuthorizeResponse_Error
	Res           isAuthorizeResponse_Res `protobuf_oneof:"res"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_core_v1_users_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizeResponse) GetRes() isAuthorizeResponse_Res {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *AuthorizeResponse) GetAuthorization() *AuthorizeResponse_Authorization {
	if x != nil {
		if x, ok := x.Res.(*AuthorizeResponse_Authorization_); ok {
			return x.Authorization
		}
	}
	return nil
}

func (x *AuthorizeResponse) GetError() string {
	if x != nil {
		if x, ok := x.Res.(*AuthorizeResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isAuthorizeResponse_Res interface {
	isAuthorizeResponse_Res()
}

type AuthorizeResponse_Authorization_ struct {
	Authorization *AuthorizeResponse_Authorization `protobuf:"bytes,1,opt,name=authorization,proto3,oneof"`
}

type AuthorizeResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*AuthorizeResponse_Authorization_) isAuthorizeResponse_Res() {}

func (*AuthorizeResponse_Error) isAuthorizeResponse_Res() {}

type AuthorizeResponse_UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse_UserResponse) Reset() {
	*x = AuthorizeResponse_UserResponse{}
	mi := &file_core_v1_users_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse_UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse_UserResponse) ProtoMessage() {}

func (x *AuthorizeResponse_UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse_UserResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse_UserResponse) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AuthorizeResponse_UserResponse) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *AuthorizeResponse_UserResponse) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *AuthorizeResponse_UserResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type AuthorizeResponse_Authorization struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	UserResponse  *AuthorizeResponse_UserResponse `protobuf:"bytes,1,opt,name=user_response,json=userResponse,proto3" json:"user_response,omitempty"`
	Token         string                          `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse_Authorization) Reset() {
	*x = AuthorizeResponse_Authorization{}
	mi := &file_core_v1_users_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse_Authorization) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse_Authorization) ProtoMessage() {}

func (x *AuthorizeResponse_Authorization) ProtoReflect() protoreflect.Message {
	mi := &file_core_v1_users_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse_Authorization.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse_Authorization) Descriptor() ([]byte, []int) {
	return file_core_v1_users_proto_rawDescGZIP(), []int{3, 1}
}

func (x *AuthorizeResponse_Authorization) GetUserResponse() *AuthorizeResponse_UserResponse {
	if x != nil {
		return x.UserResponse
	}
	return nil
}

func (x *AuthorizeResponse_Authorization) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_core_v1_users_proto protoreflect.FileDescriptor

const file_core_v1_users_proto_rawDesc = "" +
	"\n" +
	"\x13core/v1/users.proto\x12\acore.v1\x1a\x1bgoogle/protobuf/empty.proto\"\xce\x01\n" +
	"\x14CreateAccountRequest\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12!\n" +
	"\fcountry_code\x18\x05 \x01(\tR\vcountryCode\x12%\n" +
	"\x0econtact_number\x18\x06 \x01(\tR\rcontactNumber\"A\n" +
	"\x15CreateAccountResponse\x12(\n" +
	"\x03res\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03res\"D\n" +
	"\x10AuthorizeRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\xdb\x02\n" +
	"\x11AuthorizeResponse\x12P\n" +
	"\rauthorization\x18\x01 \x01(\v2(.core.v1.AuthorizeResponse.AuthorizationH\x00R\rauthorization\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x1a`\n" +
	"\fUserResponse\x12\x1d\n" +
	"\n" +
	"first_name\x18\x01 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x02 \x01(\tR\blastName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x1as\n" +
	"\rAuthorization\x12L\n" +
	"\ruser_response\x18\x01 \x01(\v2'.core.v1.AuthorizeResponse.UserResponseR\fuserResponse\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05tokenB\x05\n" +
	"\x03res2\xa2\x01\n" +
	"\fUsersService\x12N\n" +
	"\rCreateAccount\x12\x1d.core.v1.CreateAccountRequest\x1a\x1e.core.v1.CreateAccountResponse\x12B\n" +
	"\tAuthorize\x12\x19.core.v1.AuthorizeRequest\x1a\x1a.core.v1.AuthorizeResponseB\x97\x01\n" +
	"\vcom.core.v1B\n" +
	"UsersProtoP\x01Z?github.com/biswasakashdev/swiftmart/proto_gen/go/core/v1;corev1\xa2\x02\x03CXX\xaa\x02\aCore.V1\xca\x02\aCore\\V1\xe2\x02\x13Core\\V1\\GPBMetadata\xea\x02\bCore::V1b\x06proto3"

var (
	file_core_v1_users_proto_rawDescOnce sync.Once
	file_core_v1_users_proto_rawDescData []byte
)

func file_core_v1_users_proto_rawDescGZIP() []byte {
	file_core_v1_users_proto_rawDescOnce.Do(func() {
		file_core_v1_users_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_v1_users_proto_rawDesc), len(file_core_v1_users_proto_rawDesc)))
	})
	return file_core_v1_users_proto_rawDescData
}

var file_core_v1_users_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_core_v1_users_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),            // 0: core.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),           // 1: core.v1.CreateAccountResponse
	(*AuthorizeRequest)(nil),                // 2: core.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),               // 3: core.v1.AuthorizeResponse
	(*AuthorizeResponse_UserResponse)(nil),  // 4: core.v1.AuthorizeResponse.UserResponse
	(*AuthorizeResponse_Authorization)(nil), // 5: core.v1.AuthorizeResponse.Authorization
	(*emptypb.Empty)(nil),                   // 6: google.protobuf.Empty
}
var file_core_v1_users_proto_depIdxs = []int32{
	6, // 0: core.v1.CreateAccountResponse.res:type_name -> google.protobuf.Empty
	5, // 1: core.v1.AuthorizeResponse.authorization:type_name -> core.v1.AuthorizeResponse.Authorization
	4, // 2: core.v1.AuthorizeResponse.Authorization.user_response:type_name -> core.v1.AuthorizeResponse.UserResponse
	0, // 3: core.v1.UsersService.CreateAccount:input_type -> core.v1.CreateAccountRequest
	2, // 4: core.v1.UsersService.Authorize:input_type -> core.v1.AuthorizeRequest
	1, // 5: core.v1.UsersService.CreateAccount:output_type -> core.v1.CreateAccountResponse
	3, // 6: core.v1.UsersService.Authorize:output_type -> core.v1.AuthorizeResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_v1_users_proto_init() }
func file_core_v1_users_proto_init() {
	if File_core_v1_users_proto != nil {
		return
	}
	file_core_v1_users_proto_msgTypes[3].OneofWrappers = []any{
		(*AuthorizeResponse_Authorization_)(nil),
		(*AuthorizeResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_v1_users_proto_rawDesc), len(file_core_v1_users_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_v1_users_proto_goTypes,
		DependencyIndexes: file_core_v1_users_proto_depIdxs,
		MessageInfos:      file_core_v1_users_proto_msgTypes,
	}.Build()
	File_core_v1_users_proto = out.File
	file_core_v1_users_proto_goTypes = nil
	file_core_v1_users_proto_depIdxs = nil
}
