// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: catelogues/v1/products.proto

package cateloguesv1

import (
	v1 "github.com/biswasakashdev/swiftmart/proto_gen/go/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VariantMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Sku           string                 `protobuf:"bytes,2,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VariantMessage) Reset() {
	*x = VariantMessage{}
	mi := &file_catelogues_v1_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VariantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VariantMessage) ProtoMessage() {}

func (x *VariantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VariantMessage.ProtoReflect.Descriptor instead.
func (*VariantMessage) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{0}
}

func (x *VariantMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VariantMessage) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *VariantMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type CreateVariantMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           string                 `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVariantMessage) Reset() {
	*x = CreateVariantMessage{}
	mi := &file_catelogues_v1_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVariantMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVariantMessage) ProtoMessage() {}

func (x *CreateVariantMessage) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVariantMessage.ProtoReflect.Descriptor instead.
func (*CreateVariantMessage) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{1}
}

func (x *CreateVariantMessage) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateVariantMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ProductMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                 `protobuf:"bytes,4,opt,name=slug,proto3" json:"slug,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Variants      []*VariantMessage      `protobuf:"bytes,6,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProductMessage) Reset() {
	*x = ProductMessage{}
	mi := &file_catelogues_v1_products_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProductMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProductMessage) ProtoMessage() {}

func (x *ProductMessage) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProductMessage.ProtoReflect.Descriptor instead.
func (*ProductMessage) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{2}
}

func (x *ProductMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ProductMessage) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProductMessage) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProductMessage) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *ProductMessage) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ProductMessage) GetVariants() []*VariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

// Get product by id.
type GetProductByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdRequest) Reset() {
	*x = GetProductByIdRequest{}
	mi := &file_catelogues_v1_products_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdRequest) ProtoMessage() {}

func (x *GetProductByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdRequest.ProtoReflect.Descriptor instead.
func (*GetProductByIdRequest) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{3}
}

func (x *GetProductByIdRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetProductByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *ProductMessage        `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductByIdResponse) Reset() {
	*x = GetProductByIdResponse{}
	mi := &file_catelogues_v1_products_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductByIdResponse) ProtoMessage() {}

func (x *GetProductByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductByIdResponse.ProtoReflect.Descriptor instead.
func (*GetProductByIdResponse) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductByIdResponse) GetProduct() *ProductMessage {
	if x != nil {
		return x.Product
	}
	return nil
}

// Update existing variant
type UpdateVariantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VariantId     string                 `protobuf:"bytes,1,opt,name=variant_id,json=variantId,proto3" json:"variant_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Sku           *string                `protobuf:"bytes,3,opt,name=sku,proto3,oneof" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVariantRequest) Reset() {
	*x = UpdateVariantRequest{}
	mi := &file_catelogues_v1_products_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantRequest) ProtoMessage() {}

func (x *UpdateVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantRequest.ProtoReflect.Descriptor instead.
func (*UpdateVariantRequest) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateVariantRequest) GetVariantId() string {
	if x != nil {
		return x.VariantId
	}
	return ""
}

func (x *UpdateVariantRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateVariantRequest) GetSku() string {
	if x != nil && x.Sku != nil {
		return *x.Sku
	}
	return ""
}

type UpdateVariantResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VariantDetails *VariantMessage        `protobuf:"bytes,1,opt,name=variant_details,json=variantDetails,proto3" json:"variant_details,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateVariantResponse) Reset() {
	*x = UpdateVariantResponse{}
	mi := &file_catelogues_v1_products_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVariantResponse) ProtoMessage() {}

func (x *UpdateVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVariantResponse.ProtoReflect.Descriptor instead.
func (*UpdateVariantResponse) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateVariantResponse) GetVariantDetails() *VariantMessage {
	if x != nil {
		return x.VariantDetails
	}
	return nil
}

// Create new Product
type CreateProductRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Title         string                  `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                  `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Slug          string                  `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Variants      []*CreateVariantMessage `protobuf:"bytes,4,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catelogues_v1_products_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{7}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateProductRequest) GetVariants() []*CreateVariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Res           *emptypb.Empty         `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_catelogues_v1_products_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductResponse) GetRes() *emptypb.Empty {
	if x != nil {
		return x.Res
	}
	return nil
}

// Get products by query.
type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *v1.PageInfo           `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	SearchQuery   string                 `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catelogues_v1_products_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{9}
}

func (x *ListProductsRequest) GetPageInfo() *v1.PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ListProductsRequest) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*ProductMessage      `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catelogues_v1_products_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{10}
}

func (x *ListProductsResponse) GetProducts() []*ProductMessage {
	if x != nil {
		return x.Products
	}
	return nil
}

// Add new variant
type AddVariantRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	ProductId     string                  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Variants      []*CreateVariantMessage `protobuf:"bytes,2,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVariantRequest) Reset() {
	*x = AddVariantRequest{}
	mi := &file_catelogues_v1_products_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVariantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVariantRequest) ProtoMessage() {}

func (x *AddVariantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVariantRequest.ProtoReflect.Descriptor instead.
func (*AddVariantRequest) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{11}
}

func (x *AddVariantRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *AddVariantRequest) GetVariants() []*CreateVariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

type AddVariantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Variants      []*VariantMessage      `protobuf:"bytes,1,rep,name=variants,proto3" json:"variants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddVariantResponse) Reset() {
	*x = AddVariantResponse{}
	mi := &file_catelogues_v1_products_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddVariantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddVariantResponse) ProtoMessage() {}

func (x *AddVariantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catelogues_v1_products_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddVariantResponse.ProtoReflect.Descriptor instead.
func (*AddVariantResponse) Descriptor() ([]byte, []int) {
	return file_catelogues_v1_products_proto_rawDescGZIP(), []int{12}
}

func (x *AddVariantResponse) GetVariants() []*VariantMessage {
	if x != nil {
		return x.Variants
	}
	return nil
}

var File_catelogues_v1_products_proto protoreflect.FileDescriptor

const file_catelogues_v1_products_proto_rawDesc = "" +
	"\n" +
	"\x1ccatelogues/v1/products.proto\x12\rcatelogues.v1\x1a\x1bgoogle/protobuf/empty.proto\x1a\x14common/v1/main.proto\"H\n" +
	"\x0eVariantMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x10\n" +
	"\x03sku\x18\x02 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\">\n" +
	"\x14CreateVariantMessage\x12\x10\n" +
	"\x03sku\x18\x01 \x01(\tR\x03sku\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\"\xbf\x01\n" +
	"\x0eProductMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x04 \x01(\tR\x04slug\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\bvariants\x18\x06 \x03(\v2\x1d.catelogues.v1.VariantMessageR\bvariants\"'\n" +
	"\x15GetProductByIdRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"Q\n" +
	"\x16GetProductByIdResponse\x127\n" +
	"\aproduct\x18\x01 \x01(\v2\x1d.catelogues.v1.ProductMessageR\aproduct\"y\n" +
	"\x14UpdateVariantRequest\x12\x1d\n" +
	"\n" +
	"variant_id\x18\x01 \x01(\tR\tvariantId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x15\n" +
	"\x03sku\x18\x03 \x01(\tH\x01R\x03sku\x88\x01\x01B\b\n" +
	"\x06_titleB\x06\n" +
	"\x04_sku\"_\n" +
	"\x15UpdateVariantResponse\x12F\n" +
	"\x0fvariant_details\x18\x01 \x01(\v2\x1d.catelogues.v1.VariantMessageR\x0evariantDetails\"\xa3\x01\n" +
	"\x14CreateProductRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12?\n" +
	"\bvariants\x18\x04 \x03(\v2#.catelogues.v1.CreateVariantMessageR\bvariants\"A\n" +
	"\x15CreateProductResponse\x12(\n" +
	"\x03res\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x03res\"j\n" +
	"\x13ListProductsRequest\x120\n" +
	"\tpage_info\x18\x01 \x01(\v2\x13.common.v1.PageInfoR\bpageInfo\x12!\n" +
	"\fsearch_query\x18\x02 \x01(\tR\vsearchQuery\"Q\n" +
	"\x14ListProductsResponse\x129\n" +
	"\bproducts\x18\x01 \x03(\v2\x1d.catelogues.v1.ProductMessageR\bproducts\"s\n" +
	"\x11AddVariantRequest\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12?\n" +
	"\bvariants\x18\x02 \x03(\v2#.catelogues.v1.CreateVariantMessageR\bvariants\"O\n" +
	"\x12AddVariantResponse\x129\n" +
	"\bvariants\x18\x01 \x03(\v2\x1d.catelogues.v1.VariantMessageR\bvariants2\xd4\x03\n" +
	"\x0fProductsService\x12]\n" +
	"\x0eGetProductById\x12$.catelogues.v1.GetProductByIdRequest\x1a%.catelogues.v1.GetProductByIdResponse\x12W\n" +
	"\fListProducts\x12\".catelogues.v1.ListProductsRequest\x1a#.catelogues.v1.ListProductsResponse\x12Z\n" +
	"\rCreateProduct\x12#.catelogues.v1.CreateProductRequest\x1a$.catelogues.v1.CreateProductResponse\x12Z\n" +
	"\rUpdateVariant\x12#.catelogues.v1.UpdateVariantRequest\x1a$.catelogues.v1.UpdateVariantResponse\x12Q\n" +
	"\n" +
	"AddVariant\x12 .catelogues.v1.AddVariantRequest\x1a!.catelogues.v1.AddVariantResponseB\xc4\x01\n" +
	"\x11com.catelogues.v1B\rProductsProtoP\x01ZKgithub.com/biswasakashdev/swiftmart/proto_gen/go/catelogues/v1;cateloguesv1\xa2\x02\x03CXX\xaa\x02\rCatelogues.V1\xca\x02\rCatelogues\\V1\xe2\x02\x19Catelogues\\V1\\GPBMetadata\xea\x02\x0eCatelogues::V1b\x06proto3"

var (
	file_catelogues_v1_products_proto_rawDescOnce sync.Once
	file_catelogues_v1_products_proto_rawDescData []byte
)

func file_catelogues_v1_products_proto_rawDescGZIP() []byte {
	file_catelogues_v1_products_proto_rawDescOnce.Do(func() {
		file_catelogues_v1_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catelogues_v1_products_proto_rawDesc), len(file_catelogues_v1_products_proto_rawDesc)))
	})
	return file_catelogues_v1_products_proto_rawDescData
}

var file_catelogues_v1_products_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_catelogues_v1_products_proto_goTypes = []any{
	(*VariantMessage)(nil),         // 0: catelogues.v1.VariantMessage
	(*CreateVariantMessage)(nil),   // 1: catelogues.v1.CreateVariantMessage
	(*ProductMessage)(nil),         // 2: catelogues.v1.ProductMessage
	(*GetProductByIdRequest)(nil),  // 3: catelogues.v1.GetProductByIdRequest
	(*GetProductByIdResponse)(nil), // 4: catelogues.v1.GetProductByIdResponse
	(*UpdateVariantRequest)(nil),   // 5: catelogues.v1.UpdateVariantRequest
	(*UpdateVariantResponse)(nil),  // 6: catelogues.v1.UpdateVariantResponse
	(*CreateProductRequest)(nil),   // 7: catelogues.v1.CreateProductRequest
	(*CreateProductResponse)(nil),  // 8: catelogues.v1.CreateProductResponse
	(*ListProductsRequest)(nil),    // 9: catelogues.v1.ListProductsRequest
	(*ListProductsResponse)(nil),   // 10: catelogues.v1.ListProductsResponse
	(*AddVariantRequest)(nil),      // 11: catelogues.v1.AddVariantRequest
	(*AddVariantResponse)(nil),     // 12: catelogues.v1.AddVariantResponse
	(*emptypb.Empty)(nil),          // 13: google.protobuf.Empty
	(*v1.PageInfo)(nil),            // 14: common.v1.PageInfo
}
var file_catelogues_v1_products_proto_depIdxs = []int32{
	0,  // 0: catelogues.v1.ProductMessage.variants:type_name -> catelogues.v1.VariantMessage
	2,  // 1: catelogues.v1.GetProductByIdResponse.product:type_name -> catelogues.v1.ProductMessage
	0,  // 2: catelogues.v1.UpdateVariantResponse.variant_details:type_name -> catelogues.v1.VariantMessage
	1,  // 3: catelogues.v1.CreateProductRequest.variants:type_name -> catelogues.v1.CreateVariantMessage
	13, // 4: catelogues.v1.CreateProductResponse.res:type_name -> google.protobuf.Empty
	14, // 5: catelogues.v1.ListProductsRequest.page_info:type_name -> common.v1.PageInfo
	2,  // 6: catelogues.v1.ListProductsResponse.products:type_name -> catelogues.v1.ProductMessage
	1,  // 7: catelogues.v1.AddVariantRequest.variants:type_name -> catelogues.v1.CreateVariantMessage
	0,  // 8: catelogues.v1.AddVariantResponse.variants:type_name -> catelogues.v1.VariantMessage
	3,  // 9: catelogues.v1.ProductsService.GetProductById:input_type -> catelogues.v1.GetProductByIdRequest
	9,  // 10: catelogues.v1.ProductsService.ListProducts:input_type -> catelogues.v1.ListProductsRequest
	7,  // 11: catelogues.v1.ProductsService.CreateProduct:input_type -> catelogues.v1.CreateProductRequest
	5,  // 12: catelogues.v1.ProductsService.UpdateVariant:input_type -> catelogues.v1.UpdateVariantRequest
	11, // 13: catelogues.v1.ProductsService.AddVariant:input_type -> catelogues.v1.AddVariantRequest
	4,  // 14: catelogues.v1.ProductsService.GetProductById:output_type -> catelogues.v1.GetProductByIdResponse
	10, // 15: catelogues.v1.ProductsService.ListProducts:output_type -> catelogues.v1.ListProductsResponse
	8,  // 16: catelogues.v1.ProductsService.CreateProduct:output_type -> catelogues.v1.CreateProductResponse
	6,  // 17: catelogues.v1.ProductsService.UpdateVariant:output_type -> catelogues.v1.UpdateVariantResponse
	12, // 18: catelogues.v1.ProductsService.AddVariant:output_type -> catelogues.v1.AddVariantResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_catelogues_v1_products_proto_init() }
func file_catelogues_v1_products_proto_init() {
	if File_catelogues_v1_products_proto != nil {
		return
	}
	file_catelogues_v1_products_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catelogues_v1_products_proto_rawDesc), len(file_catelogues_v1_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catelogues_v1_products_proto_goTypes,
		DependencyIndexes: file_catelogues_v1_products_proto_depIdxs,
		MessageInfos:      file_catelogues_v1_products_proto_msgTypes,
	}.Build()
	File_catelogues_v1_products_proto = out.File
	file_catelogues_v1_products_proto_goTypes = nil
	file_catelogues_v1_products_proto_depIdxs = nil
}
