// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateCustomerInput struct {
	Email     string  `json:"email"`
	FirstName *string `json:"firstName,omitempty"`
	LastName  *string `json:"lastName,omitempty"`
}

type CreateOrderInput struct {
	CustomerID string           `json:"customerId"`
	Items      []*LineItemInput `json:"items"`
}

type CreateProductInput struct {
	Title       string                `json:"title"`
	Description *string               `json:"description,omitempty"`
	Slug        string                `json:"slug"`
	Variants    []*CreateVariantInput `json:"variants"`
}

type CreateVariantInput struct {
	Sku               string  `json:"sku"`
	Price             float64 `json:"price"`
	InventoryQuantity int32   `json:"inventoryQuantity"`
	Title             string  `json:"title"`
}

type Customer struct {
	ID        string   `json:"id"`
	Email     string   `json:"email"`
	FirstName *string  `json:"firstName,omitempty"`
	LastName  *string  `json:"lastName,omitempty"`
	Orders    []*Order `json:"orders"`
	CreatedAt string   `json:"createdAt"`
}

type LineItem struct {
	ID        string  `json:"id"`
	VariantID string  `json:"variantId"`
	Title     string  `json:"title"`
	Quantity  int32   `json:"quantity"`
	Price     float64 `json:"price"`
}

type LineItemInput struct {
	VariantID string `json:"variantId"`
	Quantity  int32  `json:"quantity"`
}

type Mutation struct {
}

type Order struct {
	ID                string                 `json:"id"`
	Customer          *Customer              `json:"customer"`
	LineItems         []*LineItem            `json:"lineItems"`
	TotalPrice        float64                `json:"totalPrice"`
	FinancialStatus   OrderFinancialStatus   `json:"financialStatus"`
	FulfillmentStatus OrderFulfillmentStatus `json:"fulfillmentStatus"`
	CreatedAt         string                 `json:"createdAt"`
}

type Product struct {
	ID          string            `json:"id"`
	Title       string            `json:"title"`
	Description *string           `json:"description,omitempty"`
	Slug        string            `json:"slug"`
	Status      ProductStatus     `json:"status"`
	Variants    []*ProductVariant `json:"variants"`
	CreatedAt   string            `json:"createdAt"`
	UpdatedAt   string            `json:"updatedAt"`
}

type ProductVariant struct {
	ID                string   `json:"id"`
	Sku               string   `json:"sku"`
	Price             float64  `json:"price"`
	InventoryQuantity int32    `json:"inventoryQuantity"`
	Weight            *float64 `json:"weight,omitempty"`
	Title             string   `json:"title"`
}

type Query struct {
}

type OrderFinancialStatus string

const (
	OrderFinancialStatusPending  OrderFinancialStatus = "PENDING"
	OrderFinancialStatusPaid     OrderFinancialStatus = "PAID"
	OrderFinancialStatusRefunded OrderFinancialStatus = "REFUNDED"
)

var AllOrderFinancialStatus = []OrderFinancialStatus{
	OrderFinancialStatusPending,
	OrderFinancialStatusPaid,
	OrderFinancialStatusRefunded,
}

func (e OrderFinancialStatus) IsValid() bool {
	switch e {
	case OrderFinancialStatusPending, OrderFinancialStatusPaid, OrderFinancialStatusRefunded:
		return true
	}
	return false
}

func (e OrderFinancialStatus) String() string {
	return string(e)
}

func (e *OrderFinancialStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderFinancialStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderFinancialStatus", str)
	}
	return nil
}

func (e OrderFinancialStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderFinancialStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderFinancialStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type OrderFulfillmentStatus string

const (
	OrderFulfillmentStatusUnfulfilled        OrderFulfillmentStatus = "UNFULFILLED"
	OrderFulfillmentStatusPartiallyFulfilled OrderFulfillmentStatus = "PARTIALLY_FULFILLED"
	OrderFulfillmentStatusFulfilled          OrderFulfillmentStatus = "FULFILLED"
)

var AllOrderFulfillmentStatus = []OrderFulfillmentStatus{
	OrderFulfillmentStatusUnfulfilled,
	OrderFulfillmentStatusPartiallyFulfilled,
	OrderFulfillmentStatusFulfilled,
}

func (e OrderFulfillmentStatus) IsValid() bool {
	switch e {
	case OrderFulfillmentStatusUnfulfilled, OrderFulfillmentStatusPartiallyFulfilled, OrderFulfillmentStatusFulfilled:
		return true
	}
	return false
}

func (e OrderFulfillmentStatus) String() string {
	return string(e)
}

func (e *OrderFulfillmentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = OrderFulfillmentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid OrderFulfillmentStatus", str)
	}
	return nil
}

func (e OrderFulfillmentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *OrderFulfillmentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e OrderFulfillmentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProductStatus string

const (
	ProductStatusDraft    ProductStatus = "DRAFT"
	ProductStatusActive   ProductStatus = "ACTIVE"
	ProductStatusArchived ProductStatus = "ARCHIVED"
)

var AllProductStatus = []ProductStatus{
	ProductStatusDraft,
	ProductStatusActive,
	ProductStatusArchived,
}

func (e ProductStatus) IsValid() bool {
	switch e {
	case ProductStatusDraft, ProductStatusActive, ProductStatusArchived:
		return true
	}
	return false
}

func (e ProductStatus) String() string {
	return string(e)
}

func (e *ProductStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProductStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProductStatus", str)
	}
	return nil
}

func (e ProductStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProductStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProductStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
