type Order {
    id: ID!
    customer: Customer!
    lineItems: [LineItem!]!
    totalPrice: Float!
    financialStatus: OrderFinancialStatus!
    fulfillmentStatus: OrderFulfillmentStatus!
    createdAt: String!
}
enum OrderFinancialStatus {
    PENDING
    PAID
    REFUNDED
}

enum OrderFulfillmentStatus {
    UNFULFILLED
    PARTIALLY_FULFILLED
    FULFILLED
}


type LineItem {
    id: ID!
    variantId: ID!
    title: String!
    quantity: Int!
    price: Float!
}

type OrderList{
    pageDetails: PageDetails!
    content : [Order!]!
}

# Mutatio inputs

input LineItemInput {
    productId:ID!
    variantId: ID!
}
input CreateOrderInput {
    customerId: ID!
    items: [LineItemInput!]!
}


extend type Query{

    getOrder(shopId:ID!, id: ID!): Order

    getOrdersAdmin(shopId:ID!, pageInfo:PageInfo!): OrderList

    getOrderCustomer(shopId:ID!, pageInfo:PageInfo!, customerId:ID!): OrderList

}

extend type Mutation{
    createOrder(input: CreateOrderInput!): Order!

    cancelOrder(orderId: ID!): Order!
}