// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: users/v1/main.proto

package productsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_users_v1_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_users_v1_main_proto_rawDescGZIP(), []int{0}
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_users_v1_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_users_v1_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_users_v1_main_proto_rawDescGZIP(), []int{1}
}

var File_users_v1_main_proto protoreflect.FileDescriptor

const file_users_v1_main_proto_rawDesc = "" +
	"\n" +
	"\x13users/v1/main.proto\x12\busers.v1\"\x16\n" +
	"\x14CreateAccountRequest\"\x17\n" +
	"\x15CreateAccountResponse2`\n" +
	"\fUsersService\x12P\n" +
	"\rCreateAccount\x12\x1e.users.v1.CreateAccountRequest\x1a\x1f.users.v1.CreateAccountResponseB\xa0\x01\n" +
	"\fcom.users.v1B\tMainProtoP\x01ZDgithub.com/biswasakashdev/swiftmart/services/gpql-gateway;productsv1\xa2\x02\x03UXX\xaa\x02\bUsers.V1\xca\x02\bUsers\\V1\xe2\x02\x14Users\\V1\\GPBMetadata\xea\x02\tUsers::V1b\x06proto3"

var (
	file_users_v1_main_proto_rawDescOnce sync.Once
	file_users_v1_main_proto_rawDescData []byte
)

func file_users_v1_main_proto_rawDescGZIP() []byte {
	file_users_v1_main_proto_rawDescOnce.Do(func() {
		file_users_v1_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_users_v1_main_proto_rawDesc), len(file_users_v1_main_proto_rawDesc)))
	})
	return file_users_v1_main_proto_rawDescData
}

var file_users_v1_main_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_users_v1_main_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: users.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: users.v1.CreateAccountResponse
}
var file_users_v1_main_proto_depIdxs = []int32{
	0, // 0: users.v1.UsersService.CreateAccount:input_type -> users.v1.CreateAccountRequest
	1, // 1: users.v1.UsersService.CreateAccount:output_type -> users.v1.CreateAccountResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_users_v1_main_proto_init() }
func file_users_v1_main_proto_init() {
	if File_users_v1_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_users_v1_main_proto_rawDesc), len(file_users_v1_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_users_v1_main_proto_goTypes,
		DependencyIndexes: file_users_v1_main_proto_depIdxs,
		MessageInfos:      file_users_v1_main_proto_msgTypes,
	}.Build()
	File_users_v1_main_proto = out.File
	file_users_v1_main_proto_goTypes = nil
	file_users_v1_main_proto_depIdxs = nil
}
