syntax = "proto3";


package accounts.v1.users;

import "types/v1/users.proto";

option go_package = "accountsv1";
option java_package = "com.biswasakashdev.swiftmart.protogen.accounts.v1";
option java_multiple_files = true;



service UserService {
  rpc GetUser(GetUserRequest) returns (GetUserResponse);

  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse);

  rpc Verify(VerifyRequest) returns(VerifyResponse);
}

message CreateUserRequest {
  string email = 1;
  string first_name = 2;
  string last_name = 3;
  string password = 4;
}

message CreateUserResponse {
  types.v1.users.UsersProto user = 1;
}

message GetUserRequest {
  string user_id = 1;
}

message GetUserResponse {
  types.v1.users.UsersProto user = 1;
}

message VerifyRequest{
  string email = 1;
  string password = 2;
}
message VerifyResponse{
  types.v1.users.UsersProto user = 1;
}
