// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

import (
	"bytes"
	"context"
	"fmt"
	"sync/atomic"

	"github.com/99designs/gqlgen/graphql"
	"github.com/biswasakashdev/swiftmart/services/gateway/internal/graph/model"
	gqlparser "github.com/vektah/gqlparser/v2"
	"github.com/vektah/gqlparser/v2/ast"
)

// NewExecutableSchema creates an ExecutableSchema from the ResolverRoot interface.
func NewExecutableSchema(cfg Config) graphql.ExecutableSchema {
	return &executableSchema{SchemaData: cfg.Schema, Resolvers: cfg.Resolvers, Directives: cfg.Directives, ComplexityRoot: cfg.Complexity}
}

type Config = graphql.Config[ResolverRoot, DirectiveRoot, ComplexityRoot]

type ResolverRoot interface {
	Mutation() MutationResolver
	Query() QueryResolver
}

type DirectiveRoot struct {
}

type ComplexityRoot struct {
	Customer struct {
		ID func(childComplexity int) int
	}

	LineItem struct {
		ID        func(childComplexity int) int
		Price     func(childComplexity int) int
		Quantity  func(childComplexity int) int
		Title     func(childComplexity int) int
		VariantID func(childComplexity int) int
	}

	Mutation struct {
		CancelOrder   func(childComplexity int, orderID string) int
		CreateOrder   func(childComplexity int, input model.CreateOrderInput) int
		CreateProduct func(childComplexity int, input model.CreateProductInput) int
		CreateShop    func(childComplexity int, inp model.CreateShopInput) int
		UpdateStock   func(childComplexity int, shopID string, variantID string, quantityDelta int32) int
	}

	Order struct {
		CreatedAt         func(childComplexity int) int
		Customer          func(childComplexity int) int
		FinancialStatus   func(childComplexity int) int
		FulfillmentStatus func(childComplexity int) int
		ID                func(childComplexity int) int
		LineItems         func(childComplexity int) int
		TotalPrice        func(childComplexity int) int
	}

	OrderList struct {
		Content     func(childComplexity int) int
		PageDetails func(childComplexity int) int
	}

	PageDetails struct {
		IsLast        func(childComplexity int) int
		Page          func(childComplexity int) int
		Size          func(childComplexity int) int
		TotalElements func(childComplexity int) int
	}

	Product struct {
		CreatedAt   func(childComplexity int) int
		Description func(childComplexity int) int
		ID          func(childComplexity int) int
		Slug        func(childComplexity int) int
		Status      func(childComplexity int) int
		Title       func(childComplexity int) int
		UpdatedAt   func(childComplexity int) int
		Variants    func(childComplexity int) int
	}

	ProductList struct {
		Content     func(childComplexity int) int
		PageDetails func(childComplexity int) int
	}

	ProductVariant struct {
		ID                func(childComplexity int) int
		InventoryQuantity func(childComplexity int) int
		Price             func(childComplexity int) int
		Sku               func(childComplexity int) int
		Title             func(childComplexity int) int
		Weight            func(childComplexity int) int
	}

	Query struct {
		GetOrder         func(childComplexity int, shopID string, id string) int
		GetOrderCustomer func(childComplexity int, shopID string, pageInfo model.PageInfo, customerID string) int
		GetOrdersAdmin   func(childComplexity int, shopID string, pageInfo model.PageInfo) int
		Product          func(childComplexity int, shopID string, id string) int
		Products         func(childComplexity int, shopID string, pageInfo model.PageInfo, query *string) int
		Shop             func(childComplexity int, shopID string) int
		Shops            func(childComplexity int, pageInfo model.PageInfo) int
		User             func(childComplexity int) int
	}

	Shop struct {
		ID           func(childComplexity int) int
		LastActive   func(childComplexity int) int
		Name         func(childComplexity int) int
		OrderCount   func(childComplexity int) int
		ProductCount func(childComplexity int) int
		Revenue      func(childComplexity int) int
		Role         func(childComplexity int) int
		Status       func(childComplexity int) int
	}

	ShopList struct {
		Content     func(childComplexity int) int
		PageDetails func(childComplexity int) int
	}

	User struct {
		Avatar      func(childComplexity int) int
		CountryCode func(childComplexity int) int
		Email       func(childComplexity int) int
		ID          func(childComplexity int) int
		Name        func(childComplexity int) int
		Phone       func(childComplexity int) int
	}
}

type executableSchema graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot]

func (e *executableSchema) Schema() *ast.Schema {
	if e.SchemaData != nil {
		return e.SchemaData
	}
	return parsedSchema
}

func (e *executableSchema) Complexity(ctx context.Context, typeName, field string, childComplexity int, rawArgs map[string]any) (int, bool) {
	ec := newExecutionContext(nil, e, nil)
	_ = ec
	switch typeName + "." + field {

	case "Customer.id":
		if e.ComplexityRoot.Customer.ID == nil {
			break
		}

		return e.ComplexityRoot.Customer.ID(childComplexity), true

	case "LineItem.id":
		if e.ComplexityRoot.LineItem.ID == nil {
			break
		}

		return e.ComplexityRoot.LineItem.ID(childComplexity), true
	case "LineItem.price":
		if e.ComplexityRoot.LineItem.Price == nil {
			break
		}

		return e.ComplexityRoot.LineItem.Price(childComplexity), true
	case "LineItem.quantity":
		if e.ComplexityRoot.LineItem.Quantity == nil {
			break
		}

		return e.ComplexityRoot.LineItem.Quantity(childComplexity), true
	case "LineItem.title":
		if e.ComplexityRoot.LineItem.Title == nil {
			break
		}

		return e.ComplexityRoot.LineItem.Title(childComplexity), true
	case "LineItem.variantId":
		if e.ComplexityRoot.LineItem.VariantID == nil {
			break
		}

		return e.ComplexityRoot.LineItem.VariantID(childComplexity), true

	case "Mutation.cancelOrder":
		if e.ComplexityRoot.Mutation.CancelOrder == nil {
			break
		}

		args, err := ec.field_Mutation_cancelOrder_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CancelOrder(childComplexity, args["orderId"].(string)), true
	case "Mutation.createOrder":
		if e.ComplexityRoot.Mutation.CreateOrder == nil {
			break
		}

		args, err := ec.field_Mutation_createOrder_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateOrder(childComplexity, args["input"].(model.CreateOrderInput)), true
	case "Mutation.createProduct":
		if e.ComplexityRoot.Mutation.CreateProduct == nil {
			break
		}

		args, err := ec.field_Mutation_createProduct_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateProduct(childComplexity, args["input"].(model.CreateProductInput)), true
	case "Mutation.createShop":
		if e.ComplexityRoot.Mutation.CreateShop == nil {
			break
		}

		args, err := ec.field_Mutation_createShop_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.CreateShop(childComplexity, args["inp"].(model.CreateShopInput)), true
	case "Mutation.updateStock":
		if e.ComplexityRoot.Mutation.UpdateStock == nil {
			break
		}

		args, err := ec.field_Mutation_updateStock_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Mutation.UpdateStock(childComplexity, args["shopId"].(string), args["variantId"].(string), args["quantityDelta"].(int32)), true

	case "Order.createdAt":
		if e.ComplexityRoot.Order.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Order.CreatedAt(childComplexity), true
	case "Order.customer":
		if e.ComplexityRoot.Order.Customer == nil {
			break
		}

		return e.ComplexityRoot.Order.Customer(childComplexity), true
	case "Order.financialStatus":
		if e.ComplexityRoot.Order.FinancialStatus == nil {
			break
		}

		return e.ComplexityRoot.Order.FinancialStatus(childComplexity), true
	case "Order.fulfillmentStatus":
		if e.ComplexityRoot.Order.FulfillmentStatus == nil {
			break
		}

		return e.ComplexityRoot.Order.FulfillmentStatus(childComplexity), true
	case "Order.id":
		if e.ComplexityRoot.Order.ID == nil {
			break
		}

		return e.ComplexityRoot.Order.ID(childComplexity), true
	case "Order.lineItems":
		if e.ComplexityRoot.Order.LineItems == nil {
			break
		}

		return e.ComplexityRoot.Order.LineItems(childComplexity), true
	case "Order.totalPrice":
		if e.ComplexityRoot.Order.TotalPrice == nil {
			break
		}

		return e.ComplexityRoot.Order.TotalPrice(childComplexity), true

	case "OrderList.content":
		if e.ComplexityRoot.OrderList.Content == nil {
			break
		}

		return e.ComplexityRoot.OrderList.Content(childComplexity), true
	case "OrderList.pageDetails":
		if e.ComplexityRoot.OrderList.PageDetails == nil {
			break
		}

		return e.ComplexityRoot.OrderList.PageDetails(childComplexity), true

	case "PageDetails.isLast":
		if e.ComplexityRoot.PageDetails.IsLast == nil {
			break
		}

		return e.ComplexityRoot.PageDetails.IsLast(childComplexity), true
	case "PageDetails.page":
		if e.ComplexityRoot.PageDetails.Page == nil {
			break
		}

		return e.ComplexityRoot.PageDetails.Page(childComplexity), true
	case "PageDetails.size":
		if e.ComplexityRoot.PageDetails.Size == nil {
			break
		}

		return e.ComplexityRoot.PageDetails.Size(childComplexity), true
	case "PageDetails.totalElements":
		if e.ComplexityRoot.PageDetails.TotalElements == nil {
			break
		}

		return e.ComplexityRoot.PageDetails.TotalElements(childComplexity), true

	case "Product.createdAt":
		if e.ComplexityRoot.Product.CreatedAt == nil {
			break
		}

		return e.ComplexityRoot.Product.CreatedAt(childComplexity), true
	case "Product.description":
		if e.ComplexityRoot.Product.Description == nil {
			break
		}

		return e.ComplexityRoot.Product.Description(childComplexity), true
	case "Product.id":
		if e.ComplexityRoot.Product.ID == nil {
			break
		}

		return e.ComplexityRoot.Product.ID(childComplexity), true
	case "Product.slug":
		if e.ComplexityRoot.Product.Slug == nil {
			break
		}

		return e.ComplexityRoot.Product.Slug(childComplexity), true
	case "Product.status":
		if e.ComplexityRoot.Product.Status == nil {
			break
		}

		return e.ComplexityRoot.Product.Status(childComplexity), true
	case "Product.title":
		if e.ComplexityRoot.Product.Title == nil {
			break
		}

		return e.ComplexityRoot.Product.Title(childComplexity), true
	case "Product.updatedAt":
		if e.ComplexityRoot.Product.UpdatedAt == nil {
			break
		}

		return e.ComplexityRoot.Product.UpdatedAt(childComplexity), true
	case "Product.variants":
		if e.ComplexityRoot.Product.Variants == nil {
			break
		}

		return e.ComplexityRoot.Product.Variants(childComplexity), true

	case "ProductList.content":
		if e.ComplexityRoot.ProductList.Content == nil {
			break
		}

		return e.ComplexityRoot.ProductList.Content(childComplexity), true
	case "ProductList.pageDetails":
		if e.ComplexityRoot.ProductList.PageDetails == nil {
			break
		}

		return e.ComplexityRoot.ProductList.PageDetails(childComplexity), true

	case "ProductVariant.id":
		if e.ComplexityRoot.ProductVariant.ID == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.ID(childComplexity), true
	case "ProductVariant.inventoryQuantity":
		if e.ComplexityRoot.ProductVariant.InventoryQuantity == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.InventoryQuantity(childComplexity), true
	case "ProductVariant.price":
		if e.ComplexityRoot.ProductVariant.Price == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.Price(childComplexity), true
	case "ProductVariant.sku":
		if e.ComplexityRoot.ProductVariant.Sku == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.Sku(childComplexity), true
	case "ProductVariant.title":
		if e.ComplexityRoot.ProductVariant.Title == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.Title(childComplexity), true
	case "ProductVariant.weight":
		if e.ComplexityRoot.ProductVariant.Weight == nil {
			break
		}

		return e.ComplexityRoot.ProductVariant.Weight(childComplexity), true

	case "Query.getOrder":
		if e.ComplexityRoot.Query.GetOrder == nil {
			break
		}

		args, err := ec.field_Query_getOrder_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.GetOrder(childComplexity, args["shopId"].(string), args["id"].(string)), true
	case "Query.getOrderCustomer":
		if e.ComplexityRoot.Query.GetOrderCustomer == nil {
			break
		}

		args, err := ec.field_Query_getOrderCustomer_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.GetOrderCustomer(childComplexity, args["shopId"].(string), args["pageInfo"].(model.PageInfo), args["customerId"].(string)), true
	case "Query.getOrdersAdmin":
		if e.ComplexityRoot.Query.GetOrdersAdmin == nil {
			break
		}

		args, err := ec.field_Query_getOrdersAdmin_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.GetOrdersAdmin(childComplexity, args["shopId"].(string), args["pageInfo"].(model.PageInfo)), true

	case "Query.product":
		if e.ComplexityRoot.Query.Product == nil {
			break
		}

		args, err := ec.field_Query_product_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Product(childComplexity, args["shopId"].(string), args["id"].(string)), true
	case "Query.products":
		if e.ComplexityRoot.Query.Products == nil {
			break
		}

		args, err := ec.field_Query_products_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Products(childComplexity, args["shopId"].(string), args["pageInfo"].(model.PageInfo), args["query"].(*string)), true
	case "Query.shop":
		if e.ComplexityRoot.Query.Shop == nil {
			break
		}

		args, err := ec.field_Query_shop_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Shop(childComplexity, args["shopId"].(string)), true
	case "Query.shops":
		if e.ComplexityRoot.Query.Shops == nil {
			break
		}

		args, err := ec.field_Query_shops_args(ctx, rawArgs)
		if err != nil {
			return 0, false
		}

		return e.ComplexityRoot.Query.Shops(childComplexity, args["pageInfo"].(model.PageInfo)), true
	case "Query.user":
		if e.ComplexityRoot.Query.User == nil {
			break
		}

		return e.ComplexityRoot.Query.User(childComplexity), true

	case "Shop.id":
		if e.ComplexityRoot.Shop.ID == nil {
			break
		}

		return e.ComplexityRoot.Shop.ID(childComplexity), true
	case "Shop.lastActive":
		if e.ComplexityRoot.Shop.LastActive == nil {
			break
		}

		return e.ComplexityRoot.Shop.LastActive(childComplexity), true
	case "Shop.name":
		if e.ComplexityRoot.Shop.Name == nil {
			break
		}

		return e.ComplexityRoot.Shop.Name(childComplexity), true
	case "Shop.orderCount":
		if e.ComplexityRoot.Shop.OrderCount == nil {
			break
		}

		return e.ComplexityRoot.Shop.OrderCount(childComplexity), true
	case "Shop.productCount":
		if e.ComplexityRoot.Shop.ProductCount == nil {
			break
		}

		return e.ComplexityRoot.Shop.ProductCount(childComplexity), true
	case "Shop.revenue":
		if e.ComplexityRoot.Shop.Revenue == nil {
			break
		}

		return e.ComplexityRoot.Shop.Revenue(childComplexity), true
	case "Shop.role":
		if e.ComplexityRoot.Shop.Role == nil {
			break
		}

		return e.ComplexityRoot.Shop.Role(childComplexity), true
	case "Shop.status":
		if e.ComplexityRoot.Shop.Status == nil {
			break
		}

		return e.ComplexityRoot.Shop.Status(childComplexity), true

	case "ShopList.content":
		if e.ComplexityRoot.ShopList.Content == nil {
			break
		}

		return e.ComplexityRoot.ShopList.Content(childComplexity), true
	case "ShopList.pageDetails":
		if e.ComplexityRoot.ShopList.PageDetails == nil {
			break
		}

		return e.ComplexityRoot.ShopList.PageDetails(childComplexity), true

	case "User.avatar":
		if e.ComplexityRoot.User.Avatar == nil {
			break
		}

		return e.ComplexityRoot.User.Avatar(childComplexity), true
	case "User.countryCode":
		if e.ComplexityRoot.User.CountryCode == nil {
			break
		}

		return e.ComplexityRoot.User.CountryCode(childComplexity), true
	case "User.email":
		if e.ComplexityRoot.User.Email == nil {
			break
		}

		return e.ComplexityRoot.User.Email(childComplexity), true
	case "User.id":
		if e.ComplexityRoot.User.ID == nil {
			break
		}

		return e.ComplexityRoot.User.ID(childComplexity), true
	case "User.name":
		if e.ComplexityRoot.User.Name == nil {
			break
		}

		return e.ComplexityRoot.User.Name(childComplexity), true
	case "User.phone":
		if e.ComplexityRoot.User.Phone == nil {
			break
		}

		return e.ComplexityRoot.User.Phone(childComplexity), true

	}
	return 0, false
}

func (e *executableSchema) Exec(ctx context.Context) graphql.ResponseHandler {
	opCtx := graphql.GetOperationContext(ctx)
	ec := newExecutionContext(opCtx, e, make(chan graphql.DeferredResult))
	inputUnmarshalMap := graphql.BuildUnmarshalerMap(
		ec.unmarshalInputCreateOrderInput,
		ec.unmarshalInputCreateProductInput,
		ec.unmarshalInputCreateShopInput,
		ec.unmarshalInputCreateVariantInput,
		ec.unmarshalInputLineItemInput,
		ec.unmarshalInputPageInfo,
	)
	first := true

	switch opCtx.Operation.Operation {
	case ast.Query:
		return func(ctx context.Context) *graphql.Response {
			var response graphql.Response
			var data graphql.Marshaler
			if first {
				first = false
				ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
				data = ec._Query(ctx, opCtx.Operation.SelectionSet)
			} else {
				if atomic.LoadInt32(&ec.PendingDeferred) > 0 {
					result := <-ec.DeferredResults
					atomic.AddInt32(&ec.PendingDeferred, -1)
					data = result.Result
					response.Path = result.Path
					response.Label = result.Label
					response.Errors = result.Errors
				} else {
					return nil
				}
			}
			var buf bytes.Buffer
			data.MarshalGQL(&buf)
			response.Data = buf.Bytes()
			if atomic.LoadInt32(&ec.Deferred) > 0 {
				hasNext := atomic.LoadInt32(&ec.PendingDeferred) > 0
				response.HasNext = &hasNext
			}

			return &response
		}
	case ast.Mutation:
		return func(ctx context.Context) *graphql.Response {
			if !first {
				return nil
			}
			first = false
			ctx = graphql.WithUnmarshalerMap(ctx, inputUnmarshalMap)
			data := ec._Mutation(ctx, opCtx.Operation.SelectionSet)
			var buf bytes.Buffer
			data.MarshalGQL(&buf)

			return &graphql.Response{
				Data: buf.Bytes(),
			}
		}

	default:
		return graphql.OneShot(graphql.ErrorResponse(ctx, "unsupported GraphQL operation"))
	}
}

type executionContext struct {
	*graphql.ExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot]
}

func newExecutionContext(
	opCtx *graphql.OperationContext,
	execSchema *executableSchema,
	deferredResults chan graphql.DeferredResult,
) *executionContext {
	return &executionContext{
		ExecutionContextState: graphql.NewExecutionContextState[ResolverRoot, DirectiveRoot, ComplexityRoot](
			opCtx,
			(*graphql.ExecutableSchemaState[ResolverRoot, DirectiveRoot, ComplexityRoot])(execSchema),
			parsedSchema,
			deferredResults,
		),
	}
}

var sources = []*ast.Source{
	{Name: "../graph/graphql/01_common.graphqls", Input: `# Types

type PageDetails {
  page: Int!
  size: Int!
  totalElements: Int!
  isLast: Boolean!
}

# Mutations

input PageInfo {
  page: Int!
  size: Int!
}
`, BuiltIn: false},
	{Name: "../graph/graphql/02_catelogues.graphqls", Input: `# -- Core Types ---

type Product {
  id: ID!
  title: String!
  description: String
  slug: String!
  status: ProductStatus!
  variants: [ProductVariant!]!
  createdAt: String!
  updatedAt: String!
}

type ProductVariant {
  id: ID!
  sku: String!
  price: Float!
  inventoryQuantity: Int!
  weight: Float
  title: String!
}

type ProductList {
  pageDetails: PageDetails!
  content: [Product!]!
}

enum ProductStatus {
  DRAFT
  ACTIVE
  ARCHIVED
}

# Input Types for Mutations

input CreateProductInput {
  title: String!
  description: String
  slug: String!
  variants: [CreateVariantInput!]!
}

input CreateVariantInput {
  sku: String!
  price: Float!
  inventoryQuantity: Int!
  title: String!
}

type Query {
  # Catalog
  product(shopId: ID!, id: ID!): Product

  products(shopId: ID!, pageInfo: PageInfo!, query: String): ProductList!
}

# Catalog Management
type Mutation {
  createProduct(input: CreateProductInput!): Product!

  updateStock(shopId: ID!, variantId: ID!, quantityDelta: Int!): ProductVariant!
}
`, BuiltIn: false},
	{Name: "../graph/graphql/03_orders.graphqls", Input: `type Customer {
  id: ID!
}

type Order {
  id: ID!
  customer: Customer!
  lineItems: [LineItem!]!
  totalPrice: Float!
  financialStatus: OrderFinancialStatus!
  fulfillmentStatus: OrderFulfillmentStatus!
  createdAt: String!
}

enum OrderFinancialStatus {
  PENDING
  PAID
  REFUNDED
}

enum OrderFulfillmentStatus {
  UNFULFILLED
  PARTIALLY_FULFILLED
  FULFILLED
}

type LineItem {
  id: ID!
  variantId: ID!
  title: String!
  quantity: Int!
  price: Float!
}

type OrderList {
  pageDetails: PageDetails!
  content: [Order!]!
}

# Mutatio inputs

input LineItemInput {
  productId: ID!
  variantId: ID!
}
input CreateOrderInput {
  customerId: ID!
  items: [LineItemInput!]!
}

extend type Query {
  getOrder(shopId: ID!, id: ID!): Order

  getOrdersAdmin(shopId: ID!, pageInfo: PageInfo!): OrderList

  getOrderCustomer(shopId: ID!, pageInfo: PageInfo!, customerId: ID!): OrderList
}

extend type Mutation {
  createOrder(input: CreateOrderInput!): Order!

  cancelOrder(orderId: ID!): Order!
}
`, BuiltIn: false},
	{Name: "../graph/graphql/04_users.graphqls", Input: `# Types

type User {
  id: ID!
  name: String!
  email: String!
  avatar: String
  countryCode: String!
  phone: String!
}

extend type Query {
  user: User!
}
`, BuiltIn: false},
	{Name: "../graph/graphql/05_shops.graphqls", Input: `# Types
type Shop {
  id: ID!
  name: String!
  role: String!
  status: String!
  revenue: Int!
  productCount: Int!
  orderCount: Int!
  lastActive: String!
}

type ShopList {
  pageDetails: PageDetails!
  content: [Shop!]!
}

# Inputs

input CreateShopInput {
  name: String!
  description: String!
}

extend type Query {
  shops(pageInfo: PageInfo!): ShopList!

  shop(shopId: String!): Shop!
}

extend type Mutation {
  createShop(inp: CreateShopInput!): Shop!
}
`, BuiltIn: false},
}
var parsedSchema = gqlparser.MustLoadSchema(sources...)

// childFields_* functions provide shared child field context lookups.
// Each function is generated once per unique object type, deduplicating the
// switch statements that were previously inlined in every fieldContext_* function.

func (ec *executionContext) childFields_Customer(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Customer_id(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Customer", field.Name)
}

func (ec *executionContext) childFields_LineItem(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_LineItem_id(ctx, field)
	case "variantId":
		return ec.fieldContext_LineItem_variantId(ctx, field)
	case "title":
		return ec.fieldContext_LineItem_title(ctx, field)
	case "quantity":
		return ec.fieldContext_LineItem_quantity(ctx, field)
	case "price":
		return ec.fieldContext_LineItem_price(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type LineItem", field.Name)
}

func (ec *executionContext) childFields_Order(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Order_id(ctx, field)
	case "customer":
		return ec.fieldContext_Order_customer(ctx, field)
	case "lineItems":
		return ec.fieldContext_Order_lineItems(ctx, field)
	case "totalPrice":
		return ec.fieldContext_Order_totalPrice(ctx, field)
	case "financialStatus":
		return ec.fieldContext_Order_financialStatus(ctx, field)
	case "fulfillmentStatus":
		return ec.fieldContext_Order_fulfillmentStatus(ctx, field)
	case "createdAt":
		return ec.fieldContext_Order_createdAt(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Order", field.Name)
}

func (ec *executionContext) childFields_OrderList(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "pageDetails":
		return ec.fieldContext_OrderList_pageDetails(ctx, field)
	case "content":
		return ec.fieldContext_OrderList_content(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type OrderList", field.Name)
}

func (ec *executionContext) childFields_PageDetails(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "page":
		return ec.fieldContext_PageDetails_page(ctx, field)
	case "size":
		return ec.fieldContext_PageDetails_size(ctx, field)
	case "totalElements":
		return ec.fieldContext_PageDetails_totalElements(ctx, field)
	case "isLast":
		return ec.fieldContext_PageDetails_isLast(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type PageDetails", field.Name)
}

func (ec *executionContext) childFields_Product(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Product_id(ctx, field)
	case "title":
		return ec.fieldContext_Product_title(ctx, field)
	case "description":
		return ec.fieldContext_Product_description(ctx, field)
	case "slug":
		return ec.fieldContext_Product_slug(ctx, field)
	case "status":
		return ec.fieldContext_Product_status(ctx, field)
	case "variants":
		return ec.fieldContext_Product_variants(ctx, field)
	case "createdAt":
		return ec.fieldContext_Product_createdAt(ctx, field)
	case "updatedAt":
		return ec.fieldContext_Product_updatedAt(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Product", field.Name)
}

func (ec *executionContext) childFields_ProductList(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "pageDetails":
		return ec.fieldContext_ProductList_pageDetails(ctx, field)
	case "content":
		return ec.fieldContext_ProductList_content(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ProductList", field.Name)
}

func (ec *executionContext) childFields_ProductVariant(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_ProductVariant_id(ctx, field)
	case "sku":
		return ec.fieldContext_ProductVariant_sku(ctx, field)
	case "price":
		return ec.fieldContext_ProductVariant_price(ctx, field)
	case "inventoryQuantity":
		return ec.fieldContext_ProductVariant_inventoryQuantity(ctx, field)
	case "weight":
		return ec.fieldContext_ProductVariant_weight(ctx, field)
	case "title":
		return ec.fieldContext_ProductVariant_title(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ProductVariant", field.Name)
}

func (ec *executionContext) childFields_Shop(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_Shop_id(ctx, field)
	case "name":
		return ec.fieldContext_Shop_name(ctx, field)
	case "role":
		return ec.fieldContext_Shop_role(ctx, field)
	case "status":
		return ec.fieldContext_Shop_status(ctx, field)
	case "revenue":
		return ec.fieldContext_Shop_revenue(ctx, field)
	case "productCount":
		return ec.fieldContext_Shop_productCount(ctx, field)
	case "orderCount":
		return ec.fieldContext_Shop_orderCount(ctx, field)
	case "lastActive":
		return ec.fieldContext_Shop_lastActive(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type Shop", field.Name)
}

func (ec *executionContext) childFields_ShopList(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "pageDetails":
		return ec.fieldContext_ShopList_pageDetails(ctx, field)
	case "content":
		return ec.fieldContext_ShopList_content(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type ShopList", field.Name)
}

func (ec *executionContext) childFields_User(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "id":
		return ec.fieldContext_User_id(ctx, field)
	case "name":
		return ec.fieldContext_User_name(ctx, field)
	case "email":
		return ec.fieldContext_User_email(ctx, field)
	case "avatar":
		return ec.fieldContext_User_avatar(ctx, field)
	case "countryCode":
		return ec.fieldContext_User_countryCode(ctx, field)
	case "phone":
		return ec.fieldContext_User_phone(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type User", field.Name)
}

func (ec *executionContext) childFields___Directive(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Directive_name(ctx, field)
	case "description":
		return ec.fieldContext___Directive_description(ctx, field)
	case "isRepeatable":
		return ec.fieldContext___Directive_isRepeatable(ctx, field)
	case "locations":
		return ec.fieldContext___Directive_locations(ctx, field)
	case "args":
		return ec.fieldContext___Directive_args(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Directive", field.Name)
}

func (ec *executionContext) childFields___EnumValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___EnumValue_name(ctx, field)
	case "description":
		return ec.fieldContext___EnumValue_description(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___EnumValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___EnumValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __EnumValue", field.Name)
}

func (ec *executionContext) childFields___Field(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___Field_name(ctx, field)
	case "description":
		return ec.fieldContext___Field_description(ctx, field)
	case "args":
		return ec.fieldContext___Field_args(ctx, field)
	case "type":
		return ec.fieldContext___Field_type(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___Field_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___Field_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Field", field.Name)
}

func (ec *executionContext) childFields___InputValue(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "name":
		return ec.fieldContext___InputValue_name(ctx, field)
	case "description":
		return ec.fieldContext___InputValue_description(ctx, field)
	case "type":
		return ec.fieldContext___InputValue_type(ctx, field)
	case "defaultValue":
		return ec.fieldContext___InputValue_defaultValue(ctx, field)
	case "isDeprecated":
		return ec.fieldContext___InputValue_isDeprecated(ctx, field)
	case "deprecationReason":
		return ec.fieldContext___InputValue_deprecationReason(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __InputValue", field.Name)
}

func (ec *executionContext) childFields___Schema(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "description":
		return ec.fieldContext___Schema_description(ctx, field)
	case "types":
		return ec.fieldContext___Schema_types(ctx, field)
	case "queryType":
		return ec.fieldContext___Schema_queryType(ctx, field)
	case "mutationType":
		return ec.fieldContext___Schema_mutationType(ctx, field)
	case "subscriptionType":
		return ec.fieldContext___Schema_subscriptionType(ctx, field)
	case "directives":
		return ec.fieldContext___Schema_directives(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Schema", field.Name)
}

func (ec *executionContext) childFields___Type(ctx context.Context, field graphql.CollectedField) (*graphql.FieldContext, error) {
	switch field.Name {
	case "kind":
		return ec.fieldContext___Type_kind(ctx, field)
	case "name":
		return ec.fieldContext___Type_name(ctx, field)
	case "description":
		return ec.fieldContext___Type_description(ctx, field)
	case "specifiedByURL":
		return ec.fieldContext___Type_specifiedByURL(ctx, field)
	case "fields":
		return ec.fieldContext___Type_fields(ctx, field)
	case "interfaces":
		return ec.fieldContext___Type_interfaces(ctx, field)
	case "possibleTypes":
		return ec.fieldContext___Type_possibleTypes(ctx, field)
	case "enumValues":
		return ec.fieldContext___Type_enumValues(ctx, field)
	case "inputFields":
		return ec.fieldContext___Type_inputFields(ctx, field)
	case "ofType":
		return ec.fieldContext___Type_ofType(ctx, field)
	case "isOneOf":
		return ec.fieldContext___Type_isOneOf(ctx, field)
	}
	return nil, fmt.Errorf("no field named %q was found under type __Type", field.Name)
}
